/**
 * Post-processing step: generate missing transitive model files.
 *
 * Orval only generates model files for schemas directly used in endpoint
 * operations. Schemas referenced only via $ref inside other schemas are
 * skipped, leaving broken imports. This script:
 *
 * 1. Scans all model files for relative imports
 * 2. Identifies imports whose target file does not exist
 * 3. Looks up the missing type in the processed OpenAPI schema
 * 4. Generates a TypeScript file that matches orval's output style
 * 5. Repeats until no new missing imports remain (transitive closure)
 */
import * as fs from 'node:fs';
import * as path from 'node:path';

const rootDir = path.resolve(import.meta.dirname, '../..');
const modelDir = path.join(rootDir, 'src/api/model');
const schemaFile = path.join(rootDir, 'src/api/schema/openapi.processed.json');

const HEADER = [
  '/**',
  ' * Generated by generate-missing-models.ts',
  ' * Stub for transitive dependency not emitted by orval.',
  ' * Do not edit manually.',
  ' */',
].join('\n');

interface SchemaObject {
  type?: string;
  enum?: string[];
  properties?: Record<string, SchemaProperty>;
  description?: string;
  nullable?: boolean;
  'x-longDescription'?: string;
  items?: SchemaProperty;
  $ref?: string;
}

interface SchemaProperty {
  type?: string;
  $ref?: string;
  description?: string;
  nullable?: boolean;
  readOnly?: boolean;
  enum?: string[];
  items?: SchemaProperty;
  format?: string;
  anyOf?: SchemaProperty[];
  oneOf?: SchemaProperty[];
}

/**
 * Resolve a schema name to its key in the processed schema.
 * Orval PascalCase-ifies names, so `Circuit_NominalVoltageType` becomes
 * `CircuitNominalVoltageType` in the model filename. We try exact match
 * first, then fall back to case-insensitive underscore-stripped matching.
 */
function resolveSchemaKey(
  name: string,
  schemaKeys: string[],
): string | undefined {
  // Exact match
  if (schemaKeys.includes(name)) return name;
  // Strip underscores and compare case-insensitively
  const stripped = name.replace(/_/g, '').toLowerCase();
  return schemaKeys.find(
    (k) => k.replace(/_/g, '').toLowerCase() === stripped,
  );
}

/**
 * Map a JSON Schema type to a TypeScript type string.
 */
function tsType(prop: SchemaProperty, _schemas: Record<string, SchemaObject>): string {
  if (prop.$ref) {
    // Extract name from #/components/schemas/Foo
    const refName = prop.$ref.split('/').pop()!;
    return toPascalCase(refName);
  }
  if (prop.anyOf || prop.oneOf) {
    const variants = (prop.anyOf || prop.oneOf)!;
    const types = variants.map((v) => tsType(v, _schemas));
    return types.join(' | ');
  }
  if (prop.enum) {
    return prop.enum.map((v) => `'${v}'`).join(' | ');
  }
  switch (prop.type) {
    case 'string':
      return 'string';
    case 'integer':
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      if (prop.items) {
        return `${tsType(prop.items, _schemas)}[]`;
      }
      return 'unknown[]';
    case 'object':
      return 'Record<string, unknown>';
    default:
      return 'unknown';
  }
}

function toPascalCase(str: string): string {
  // Split on underscores and hyphens, capitalize each segment
  return str
    .split(/[_-]/)
    .map((part) => (part.length > 0 ? part.charAt(0).toUpperCase() + part.slice(1) : ''))
    .join('');
}

/**
 * Check if a property name needs quoting (contains special characters).
 */
function quotePropName(name: string): string {
  if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)) return name;
  return `'${name}'`;
}

/**
 * Collect all relative import targets from a single model file that don't
 * have a corresponding .ts file on disk.
 */
function findMissingImports(filePath: string): string[] {
  const content = fs.readFileSync(filePath, 'utf-8');
  const missing: string[] = [];
  const re = /from\s+['"]\.\/([^'"]+)['"]/g;
  let m;
  while ((m = re.exec(content)) !== null) {
    const target = path.join(modelDir, m[1] + '.ts');
    if (!fs.existsSync(target)) {
      missing.push(m[1]);
    }
  }
  return missing;
}

/**
 * Generate a TypeScript model file for a schema.
 */
function generateModelFile(
  name: string,
  schema: SchemaObject,
  allSchemas: Record<string, SchemaObject>,
): string {
  const lines: string[] = [HEADER, ''];

  // Enum type → export a string literal union
  if (schema.enum && (schema.type === 'string' || !schema.type)) {
    const values = schema.enum.map((v) => `  | '${v}'`).join('\n');
    if (schema.description) {
      lines.push(`/** ${schema.description} */`);
    }
    lines.push(`export type ${name} =\n${values};\n`);
    return lines.join('\n');
  }

  // Simple scalar type
  if (schema.type && !schema.properties && !schema.enum) {
    let base: string;
    switch (schema.type) {
      case 'integer':
      case 'number':
        base = 'number';
        break;
      case 'boolean':
        base = 'boolean';
        break;
      default:
        base = 'string';
    }
    if (schema.description) {
      lines.push(`/** ${schema.description} */`);
    }
    lines.push(`export type ${name} = ${base};\n`);
    return lines.join('\n');
  }

  // Object type → export an interface
  // Collect imports for $ref properties
  const imports = new Map<string, string>(); // importName -> moduleName
  if (schema.properties) {
    for (const prop of Object.values(schema.properties)) {
      collectRefs(prop, imports);
    }
  }

  // Write import statements
  for (const [importName, moduleName] of [...imports].sort((a, b) =>
    a[0].localeCompare(b[0]),
  )) {
    lines.push(
      `import type { ${importName} } from './${moduleName}';`,
    );
  }
  if (imports.size > 0) lines.push('');

  // Write interface
  if (schema.description) {
    lines.push(`/** ${schema.description} */`);
  }
  lines.push(`export interface ${name} {`);

  if (schema.properties) {
    for (const [propName, prop] of Object.entries(schema.properties)) {
      const optional = !prop.readOnly ? '?' : '';
      const readonly = prop.readOnly ? 'readonly ' : '';
      const nullable = prop.nullable ? ' | null' : '';
      const type = tsType(prop, allSchemas);
      const quoted = quotePropName(propName);

      if (prop.description) {
        lines.push(`    /** ${prop.description} */`);
      }
      if (prop.nullable) {
        lines.push(`    /** @nullable */`);
      }
      lines.push(
        `    ${readonly}${quoted}${optional}: ${type}${nullable};`,
      );
    }
  }

  lines.push('}', '');
  return lines.join('\n');
}

/**
 * Recursively collect $ref type names from a property.
 */
function collectRefs(
  prop: SchemaProperty,
  imports: Map<string, string>,
): void {
  if (prop.$ref) {
    const raw = prop.$ref.split('/').pop()!;
    const name = toPascalCase(raw);
    imports.set(name, name);
  }
  if (prop.items) collectRefs(prop.items, imports);
  if (prop.anyOf) prop.anyOf.forEach((v) => collectRefs(v, imports));
  if (prop.oneOf) prop.oneOf.forEach((v) => collectRefs(v, imports));
}

async function main() {
  console.log('\n🔧 Generating missing transitive model files...');

  if (!fs.existsSync(schemaFile)) {
    console.log('   ⚠️  Processed schema not found, skipping');
    return;
  }

  const schema = JSON.parse(fs.readFileSync(schemaFile, 'utf-8'));
  const allSchemas: Record<string, SchemaObject> =
    schema.components?.schemas || {};
  const schemaKeys = Object.keys(allSchemas);

  let totalGenerated = 0;
  let pass = 0;

  // Iterate until no new files are generated (transitive closure)
  while (true) {
    pass++;
    const allMissing = new Set<string>();

    const modelFiles = fs
      .readdirSync(modelDir)
      .filter((f) => f.endsWith('.ts'));

    for (const file of modelFiles) {
      const missing = findMissingImports(path.join(modelDir, file));
      for (const m of missing) {
        allMissing.add(m);
      }
    }

    if (allMissing.size === 0) break;

    let generated = 0;
    for (const name of [...allMissing].sort()) {
      const key = resolveSchemaKey(name, schemaKeys);
      if (!key) {
        // No schema found — generate an opaque type alias
        const content = [
          HEADER,
          '',
          `export type ${name} = unknown;`,
          '',
        ].join('\n');
        fs.writeFileSync(path.join(modelDir, `${name}.ts`), content);
        console.log(`   ⚠️  ${name} (not in schema → opaque stub)`);
        generated++;
        continue;
      }

      const schemaObj = allSchemas[key];
      const content = generateModelFile(name, schemaObj, allSchemas);
      fs.writeFileSync(path.join(modelDir, `${name}.ts`), content);
      console.log(`   ✅ ${name}`);
      generated++;
    }

    totalGenerated += generated;

    // Safety: if we generated files but there are still missing imports,
    // those new files might import yet more missing types. Loop again.
    if (generated === 0) break;
    if (pass > 10) {
      console.log('   ⚠️  Exceeded 10 passes, stopping');
      break;
    }
  }

  if (totalGenerated > 0) {
    console.log(
      `   📦 Generated ${totalGenerated} missing model file(s) in ${pass} pass(es)`,
    );

    // Update index.ts barrel to include new files
    updateBarrel();
  } else {
    console.log('   ✅ No missing model files');
  }
}

/**
 * Add export lines for newly generated files to the barrel index.ts.
 * We parse the existing index.ts to find which basenames are already
 * exported, then append any new ones.
 */
function updateBarrel() {
  const indexPath = path.join(modelDir, 'index.ts');
  if (!fs.existsSync(indexPath)) return;

  const content = fs.readFileSync(indexPath, 'utf-8');
  const existingExports = new Set<string>();
  const re = /from\s+['"]\.\/([^'"]+)['"]/g;
  let m;
  while ((m = re.exec(content)) !== null) {
    existingExports.add(m[1]);
  }

  const modelFiles = fs
    .readdirSync(modelDir)
    .filter((f) => f.endsWith('.ts') && f !== 'index.ts');

  const newExports: string[] = [];
  for (const file of modelFiles) {
    const base = file.slice(0, -3);
    if (!existingExports.has(base)) {
      newExports.push(base);
    }
  }

  if (newExports.length > 0) {
    const lines = newExports
      .sort()
      .map((n) => `export * from './${n}';`);
    fs.appendFileSync(indexPath, '\n' + lines.join('\n') + '\n');
    console.log(
      `   📝 Added ${newExports.length} export(s) to index.ts`,
    );
  }
}

main().catch(console.error);
