/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.28.0
 */
export type ChassisEnvironmentalClass =
    (typeof ChassisEnvironmentalClass)[keyof typeof ChassisEnvironmentalClass];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChassisEnvironmentalClass = {
    /** ASHRAE Environmental Class \'A1\'. */
    A1: 'A1',
    /** ASHRAE Environmental Class \'A2\'. */
    A2: 'A2',
    /** ASHRAE Environmental Class \'A3\'. */
    A3: 'A3',
    /** ASHRAE Environmental Class \'A4\'. */
    A4: 'A4',
} as const;
