/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ChassisDoorState } from './ChassisDoorState';

/**
 * A door or access panel on the chassis.
 * @version 1.28.0
 */
export interface ChassisDoor {
    /**
     * The state of the door.
     * @nullable
     */
    readonly DoorState?: ChassisDoorState;
    /**
     * Indicates if the door is locked.
     * @nullable
     */
    Locked?: boolean | null;
    /** A user-assigned label. */
    UserLabel?: string;
}
