/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.28.0
 */
export type ChassisIntrusionSensorReArm =
    (typeof ChassisIntrusionSensorReArm)[keyof typeof ChassisIntrusionSensorReArm];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChassisIntrusionSensorReArm = {
    /** A user is required to clear the sensor to restore it to the normal state. */
    Manual: 'Manual',
    /** The sensor is automatically restored to the normal state when no security condition is detected. */
    Automatic: 'Automatic',
} as const;
