/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.28.0
 */
export type ChassisThermalDirection =
    (typeof ChassisThermalDirection)[keyof typeof ChassisThermalDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChassisThermalDirection = {
    /** A chassis with the air intake in the front and exhaust out the back. */
    FrontToBack: 'FrontToBack',
    /** A chassis with the air intake in the back and exhaust out the front. */
    BackToFront: 'BackToFront',
    /** A chassis with air exhaust on the top. */
    TopExhaust: 'TopExhaust',
    /** A sealed chassis with no air pathway. */
    Sealed: 'Sealed',
} as const;
