/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ChassisReset } from './ChassisReset';
import type { ChassisOemActions } from './ChassisOemActions';

/**
 * The available actions for this resource.
 * @version 1.28.0
 */
export interface ChassisActions {
    '#Chassis.Reset'?: ChassisReset;
    /** The available OEM-specific actions for this resource. */
    Oem?: ChassisOemActions;
}
