/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * This action resets the chassis.  Additionally, it could reset systems or other contained resources depending on the `ResetType` used to invoke this action.
 * @version 1.28.0
 */
export interface ChassisReset {
    /** Link to invoke action */
    target?: string;
    /** Friendly action name */
    title?: string;
}
