/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Context } from './OdataV4Context';
import type { OdataV4Etag } from './OdataV4Etag';
import type { OdataV4Id } from './OdataV4Id';
import type { OdataV4Type } from './OdataV4Type';
import type { ChassisActions } from './ChassisActions';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { ChassisType } from './ChassisType';
import type { ResourceDescription } from './ResourceDescription';
import type { ChassisDoors } from './ChassisDoors';
import type { ChassisEnvironmentalClass } from './ChassisEnvironmentalClass';
import type { ResourceId } from './ResourceId';
import type { ChassisIndicatorLED } from './ChassisIndicatorLED';
import type { ChassisLinks } from './ChassisLinks';
import type { ResourceLocation } from './ResourceLocation';
import type { SoftwareInventoryMeasurementBlock } from './SoftwareInventoryMeasurementBlock';
import type { ResourceName } from './ResourceName';
import type { ResourceOem } from './ResourceOem';
import type { ChassisPhysicalSecurity } from './ChassisPhysicalSecurity';
import type { ResourcePowerState } from './ResourcePowerState';
import type { ChassisRackMountWidth } from './ChassisRackMountWidth';
import type { ChassisRackUnits } from './ChassisRackUnits';
import type { ResourceStatus } from './ResourceStatus';
import type { ChassisThermalDirection } from './ChassisThermalDirection';
import type { ResourceUUID } from './ResourceUUID';

/**
 * The `Chassis` schema represents the physical components of a system.  This resource represents the sheet-metal confined spaces and logical zones such as racks, enclosures, chassis and all other containers.  Subsystems, such as sensors, that operate outside of a system's data plane are linked either directly or indirectly through this resource.  A subsystem that operates outside of a system's data plane are not accessible to software that runs on the system.  It also describes the location, such as a slot, socket, or bay, where a unit can be installed, by populating a resource instance with an absent state if a unit is not present.
 * @version 1.28.0
 */
export interface Chassis {
    '@odata.context'?: OdataV4Context;
    '@odata.etag'?: OdataV4Etag;
    '@odata.id': OdataV4Id;
    '@odata.type': OdataV4Type;
    /** The available actions for this resource. */
    Actions?: ChassisActions;
    /** The link to the assembly associated with this chassis. */
    readonly Assembly?: OdataV4IdRef;
    /**
     * The user-assigned asset tag of this chassis.
     * @nullable
     */
    AssetTag?: string | null;
    /** The link to a collection of certificates for device identity and attestation. */
    readonly Certificates?: OdataV4IdRef;
    /** The type of physical form factor of the chassis. */
    readonly ChassisType: ChassisType;
    /** The link to the collection of controls located in this chassis. */
    readonly Controls?: OdataV4IdRef;
    /**
     * The depth of the chassis.
     * @minimum 0
     * @nullable
     */
    readonly DepthMm?: number | null;
    /** @nullable */
    readonly Description?: ResourceDescription;
    /** The doors or access panels of the chassis. */
    Doors?: ChassisDoors;
    /** The link to the collection of drives within this chassis. */
    Drives?: OdataV4IdRef;
    /** The URIs of the management interfaces for the external electrical source connections for this chassis. */
    ElectricalSourceManagerURIs?: (string | null)[];
    /** The names of the external electrical sources, such as circuits or outlets, connected to this chassis. */
    ElectricalSourceNames?: (string | null)[];
    /** The link to the environment metrics for this chassis. */
    readonly EnvironmentMetrics?: OdataV4IdRef;
    /**
     * The ASHRAE Environmental Class for this chassis.
     * @nullable
     */
    EnvironmentalClass?: ChassisEnvironmentalClass;
    /** The link to the collection of fabric adapters located in this chassis that provide access to fabric-related resource pools. */
    readonly FabricAdapters?: OdataV4IdRef;
    /** The names of the external heating or cooling equipment, such as coolant distribution units, connected to this chassis. */
    HeatingCoolingEquipmentNames?: (string | null)[];
    /** The URIs of the management interfaces for the external heating or cooling equipment for this chassis. */
    HeatingCoolingManagerURIs?: (string | null)[];
    /**
     * The height of the chassis.
     * @minimum 0
     * @nullable
     */
    readonly HeightMm?: number | null;
    /**
     * The height of the rack-mountable chassis in rack units.
     * @nullable
     */
    readonly HeightRackUnits?: number | null;
    /**
     * An indication of whether this component can be inserted or removed while the equipment is in operation.
     * @nullable
     */
    readonly HotPluggable?: boolean | null;
    readonly Id: ResourceId;
    /**
     * The state of the indicator LED, which identifies the chassis.
     * @deprecated
     * @nullable
     */
    IndicatorLED?: ChassisIndicatorLED;
    /** The link to the collection of leak detectors located in this chassis. */
    readonly LeakDetectors?: OdataV4IdRef;
    /** The links to other resources that are related to this resource. */
    Links?: ChassisLinks;
    /** The location of the chassis. */
    Location?: ResourceLocation;
    /**
     * An indicator allowing an operator to physically locate this resource.
     * @nullable
     */
    LocationIndicatorActive?: boolean | null;
    /** The link to the logs for this chassis. */
    readonly LogServices?: OdataV4IdRef;
    /**
     * The manufacturer of this chassis.
     * @nullable
     */
    readonly Manufacturer?: string | null;
    /**
     * The upper bound of the total power consumed by the chassis.
     * @nullable
     */
    readonly MaxPowerWatts?: number | null;
    /**
     * An array of DSP0274-defined measurement blocks.
     * @deprecated
     */
    Measurements?: SoftwareInventoryMeasurementBlock[];
    /**
     * The link to the collection of media controllers located in this chassis.
     * @deprecated
     */
    readonly MediaControllers?: OdataV4IdRef;
    /** The link to the collection of memory located in this chassis that belong to fabric-related resource pools. */
    readonly Memory?: OdataV4IdRef;
    /** The link to the collection of memory domains located in this chassis that belong to fabric-related resource pools. */
    readonly MemoryDomains?: OdataV4IdRef;
    /**
     * The lower bound of the total power consumed by the chassis.
     * @nullable
     */
    readonly MinPowerWatts?: number | null;
    /**
     * The model number of the chassis.
     * @nullable
     */
    readonly Model?: string | null;
    readonly Name: ResourceName;
    /** The link to the collection of network adapters associated with this chassis. */
    readonly NetworkAdapters?: OdataV4IdRef;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** The link to the collection of PCIe devices located in this chassis. */
    readonly PCIeDevices?: OdataV4IdRef;
    /**
     * The link to the PCIe slot properties for this chassis.
     * @deprecated
     */
    readonly PCIeSlots?: OdataV4IdRef;
    /**
     * The part number of the chassis.
     * @nullable
     */
    readonly PartNumber?: string | null;
    /** The physical security state of the chassis. */
    PhysicalSecurity?: ChassisPhysicalSecurity;
    /**
     * The link to the power properties, or power supplies, power policies, and sensors, for this chassis.
     * @deprecated
     */
    readonly Power?: OdataV4IdRef;
    /**
     * The current power state of the chassis.
     * @nullable
     */
    readonly PowerState?: ResourcePowerState;
    /** The link to the power subsystem properties for this chassis. */
    readonly PowerSubsystem?: OdataV4IdRef;
    /**
     * Indicates that the chassis receives power from the containing chassis.
     * @nullable
     */
    readonly PoweredByParent?: boolean | null;
    /** The link to the collection of processors located in this chassis that belong to fabric-related resource pools. */
    readonly Processors?: OdataV4IdRef;
    /**
     * The usable capacity of rack units provided by this chassis.
     * @nullable
     */
    RackMountCapacityUnits?: number | null;
    /**
     * The usable depth of the rack-mountable area of the chassis.
     * @minimum 0
     * @nullable
     */
    RackMountDepthMm?: number | null;
    /**
     * The width of the rack-mountable chassis or rack-mounting space.
     * @nullable
     */
    RackMountWidth?: ChassisRackMountWidth;
    /**
     * The type of rack-mount units.
     * @nullable
     */
    RackUnits?: ChassisRackUnits;
    /**
     * An indication of whether the chassis is prepared by the system for removal.
     * @nullable
     */
    ReadyToRemove?: boolean | null;
    /**
     * An indication of whether this component can be independently replaced as allowed by the vendor's replacement policy.
     * @nullable
     */
    readonly Replaceable?: boolean | null;
    /**
     * The SKU of the chassis.
     * @nullable
     */
    readonly SKU?: string | null;
    /** The link to the collection of sensors located in the equipment and sub-components. */
    readonly Sensors?: OdataV4IdRef;
    /**
     * The serial number of the chassis.
     * @nullable
     */
    readonly SerialNumber?: string | null;
    /**
     * The spare part number of the chassis.
     * @nullable
     */
    readonly SparePartNumber?: string | null;
    /** The status and health of the resource and its subordinate or dependent resources. */
    Status?: ResourceStatus;
    /**
     * The link to the thermal properties, such as fans, cooling, and sensors, for this chassis.
     * @deprecated
     */
    readonly Thermal?: OdataV4IdRef;
    /**
     * Indicates the thermal management path through the chassis.
     * @nullable
     */
    readonly ThermalDirection?: ChassisThermalDirection;
    /**
     * Indicates that the chassis is thermally managed by the parent chassis.
     * @nullable
     */
    readonly ThermalManagedByParent?: boolean | null;
    /** The link to the thermal subsystem properties for this chassis. */
    readonly ThermalSubsystem?: OdataV4IdRef;
    /** The link to the trusted components in this chassis. */
    readonly TrustedComponents?: OdataV4IdRef;
    /**
     * The UUID for this chassis.
     * @nullable
     */
    readonly UUID?: ResourceUUID;
    /**
     * The hardware version of this chassis.
     * @nullable
     */
    readonly Version?: string | null;
    /**
     * The weight of the chassis.
     * @minimum 0
     * @nullable
     */
    readonly WeightKg?: number | null;
    /**
     * The width of the chassis.
     * @minimum 0
     * @nullable
     */
    readonly WidthMm?: number | null;
}
