/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.28.0
 */
export type ChassisIntrusionSensor =
    (typeof ChassisIntrusionSensor)[keyof typeof ChassisIntrusionSensor];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChassisIntrusionSensor = {
    /** No physical security condition is detected at this time. */
    Normal: 'Normal',
    /** A door, lock, or other mechanism protecting the internal system hardware from being accessed is detected to be in an insecure state. */
    HardwareIntrusion: 'HardwareIntrusion',
    /** Physical tampering of the monitored entity is detected. */
    TamperingDetected: 'TamperingDetected',
} as const;
