/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.28.0
 */
export type ChassisDoorState =
    (typeof ChassisDoorState)[keyof typeof ChassisDoorState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChassisDoorState = {
    /** Door is closed and locked. */
    Locked: 'Locked',
    /** Door is closed. */
    Closed: 'Closed',
    /** Door is open and locked. */
    LockedAndOpen: 'LockedAndOpen',
    /** Door is open. */
    Open: 'Open',
} as const;
