/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.28.0
 */
export type ChassisRackUnits =
    (typeof ChassisRackUnits)[keyof typeof ChassisRackUnits];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChassisRackUnits = {
    /** An Open Rack rack unit (48 mm or 1.89 in). */
    OpenU: 'OpenU',
    /** An EIA-310 rack unit (1.75 in or 44.45 mm). */
    EIA_310: 'EIA_310',
} as const;
