/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ChassisIntrusionSensor } from './ChassisIntrusionSensor';
import type { ChassisIntrusionSensorReArm } from './ChassisIntrusionSensorReArm';

/**
 * The physical security state of the chassis.
 * @version 1.28.0
 */
export interface ChassisPhysicalSecurity {
    /**
     * The physical security state of the chassis, such as if hardware intrusion is detected.
     * @nullable
     */
    IntrusionSensor?: ChassisIntrusionSensor;
    /**
     * A numerical identifier to represent the physical security sensor.
     * @deprecated
     * @nullable
     */
    readonly IntrusionSensorNumber?: number | null;
    /**
     * The policy that describes how the physical security state of the chassis returns to a normal state.
     * @nullable
     */
    IntrusionSensorReArm?: ChassisIntrusionSensorReArm;
}
