/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ChassisDoor } from './ChassisDoor';

/**
 * The doors or access panels of the chassis.
 * @version 1.28.0
 */
export interface ChassisDoors {
    /**
     * The front door of the chassis.
     * @nullable
     */
    Front?: ChassisDoor;
    /**
     * The rear door of the chassis.
     * @nullable
     */
    Rear?: ChassisDoor;
}
