/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.28.0
 */
export type ChassisRackMountWidth =
    (typeof ChassisRackMountWidth)[keyof typeof ChassisRackMountWidth];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChassisRackMountWidth = {
    /** Open Rack (21.0 in or 533.4 mm). */
    OpenU: 'OpenU',
    /** EIA-310 19-inch. */
    EIA_310: 'EIA_310',
    /** EIA-310 23-inch (Telco). */
    EIA_310_Telco: 'EIA_310_Telco',
    /** Half-width (~9.5 in) Unit. */
    HalfWidth: 'HalfWidth',
} as const;
