/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { OdataV4Count } from './OdataV4Count';
import type { ResourceOem } from './ResourceOem';

/**
 * The links to other resources that are related to this resource.
 * @version 1.28.0
 */
export interface ChassisLinks {
    /** An array of links to the automation nodes contained in this chassis. */
    readonly AutomationNodes?: readonly OdataV4IdRef[];
    'AutomationNodes@odata.count'?: OdataV4Count;
    /** An array of links to the cables connected to this chassis. */
    readonly Cables?: readonly OdataV4IdRef[];
    'Cables@odata.count'?: OdataV4Count;
    /** An array of links to the computer systems that this chassis directly and wholly contains. */
    readonly ComputerSystems?: readonly OdataV4IdRef[];
    'ComputerSystems@odata.count'?: OdataV4Count;
    /** An array of links to cooling loops connected to this chassis. */
    ConnectedCoolingLoops?: OdataV4IdRef[];
    'ConnectedCoolingLoops@odata.count'?: OdataV4Count;
    /** The link to the chassis that contains this chassis. */
    ContainedBy?: OdataV4IdRef;
    /** An array of links to any other chassis that this chassis has in it. */
    Contains?: OdataV4IdRef[];
    'Contains@odata.count'?: OdataV4Count;
    /**
     * An array of links to resources or objects that cool this chassis.  Normally, the link is for either a chassis or a specific set of fans.
     * @deprecated
     */
    readonly CooledBy?: readonly OdataV4IdRef[];
    'CooledBy@odata.count'?: OdataV4Count;
    /** An array of links to cooling unit functionality contained in this chassis. */
    CoolingUnits?: OdataV4IdRef[];
    'CoolingUnits@odata.count'?: OdataV4Count;
    /** An array of links to the drives located in this chassis. */
    readonly Drives?: readonly OdataV4IdRef[];
    'Drives@odata.count'?: OdataV4Count;
    /** The link to the facility that contains this chassis. */
    Facility?: OdataV4IdRef;
    /** An array of links to the fans that cool this chassis. */
    readonly Fans?: readonly OdataV4IdRef[];
    'Fans@odata.count'?: OdataV4Count;
    /** An array of links to the managers responsible for managing this chassis. */
    readonly ManagedBy?: readonly OdataV4IdRef[];
    'ManagedBy@odata.count'?: OdataV4Count;
    /** An array of links to the managers located in this chassis. */
    readonly ManagersInChassis?: readonly OdataV4IdRef[];
    'ManagersInChassis@odata.count'?: OdataV4Count;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * An array of links to the PCIe devices located in this chassis.
     * @deprecated
     */
    readonly PCIeDevices?: readonly OdataV4IdRef[];
    'PCIeDevices@odata.count'?: OdataV4Count;
    /**
     * A link to power distribution functionality contained in this chassis.
     * @nullable
     */
    readonly PowerDistribution?: OdataV4IdRef;
    /** An array of links to the outlets that provide power to this chassis. */
    PowerOutlets?: OdataV4IdRef[];
    'PowerOutlets@odata.count'?: OdataV4Count;
    /** An array of links to the power supplies that provide power to this chassis. */
    readonly PowerSupplies?: readonly OdataV4IdRef[];
    'PowerSupplies@odata.count'?: OdataV4Count;
    /**
     * An array of links to resources or objects that power this chassis.  Normally, the link is for either a chassis or a specific set of power supplies.
     * @deprecated
     */
    readonly PoweredBy?: readonly OdataV4IdRef[];
    'PoweredBy@odata.count'?: OdataV4Count;
    /** An array of links to the processors located in this chassis. */
    readonly Processors?: readonly OdataV4IdRef[];
    'Processors@odata.count'?: OdataV4Count;
    /** An array of links to the resource blocks located in this chassis. */
    readonly ResourceBlocks?: readonly OdataV4IdRef[];
    'ResourceBlocks@odata.count'?: OdataV4Count;
    /** An array of links to the storage subsystems connected to or inside this chassis. */
    readonly Storage?: readonly OdataV4IdRef[];
    'Storage@odata.count'?: OdataV4Count;
    /** An array of links to the switches located in this chassis. */
    readonly Switches?: readonly OdataV4IdRef[];
    'Switches@odata.count'?: OdataV4Count;
}
