/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.28.0
 */
export type ChassisType = (typeof ChassisType)[keyof typeof ChassisType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChassisType = {
    /** An equipment rack, typically a 19-inch wide freestanding unit. */
    Rack: 'Rack',
    /** An enclosed or semi-enclosed, typically vertically-oriented, system chassis that must be plugged into a multi-system chassis to function normally. */
    Blade: 'Blade',
    /** A generic term for a chassis that does not fit any other description. */
    Enclosure: 'Enclosure',
    /** A single, free-standing system, commonly called a tower or desktop chassis. */
    StandAlone: 'StandAlone',
    /** A single-system chassis designed specifically for mounting in an equipment rack. */
    RackMount: 'RackMount',
    /** A loose device or circuit board intended to be installed in a system or other enclosure. */
    Card: 'Card',
    /** A small self-contained system intended to be plugged into a multi-system chassis. */
    Cartridge: 'Cartridge',
    /** A collection of equipment racks. */
    Row: 'Row',
    /** A collection of equipment racks in a large, likely transportable, container. */
    Pod: 'Pod',
    /** A chassis that expands the capabilities or capacity of another chassis. */
    Expansion: 'Expansion',
    /** A chassis that mates mechanically with another chassis to expand its capabilities or capacity. */
    Sidecar: 'Sidecar',
    /** A logical division or portion of a physical chassis that contains multiple devices or systems that cannot be physically separated. */
    Zone: 'Zone',
    /** An enclosed or semi-enclosed, system chassis that must be plugged into a multi-system chassis to function normally similar to a blade type chassis. */
    Sled: 'Sled',
    /** An enclosed or semi-enclosed, typically horizontally-oriented, system chassis that must be plugged into a multi-system chassis to function normally. */
    Shelf: 'Shelf',
    /** An enclosed or semi-enclosed, typically horizontally-oriented, system chassis that can be slid into a multi-system chassis. */
    Drawer: 'Drawer',
    /** A small, typically removable, chassis or card that contains devices for a particular subsystem or function. */
    Module: 'Module',
    /** A small chassis, card, or device that contains devices for a particular subsystem or function. */
    Component: 'Component',
    /** A chassis in a drive form factor with IP-based network connections. */
    IPBasedDrive: 'IPBasedDrive',
    /** A group of racks that form a single entity or share infrastructure. */
    RackGroup: 'RackGroup',
    /** A chassis that encloses storage. */
    StorageEnclosure: 'StorageEnclosure',
    /** An immersion cooling tank. */
    ImmersionTank: 'ImmersionTank',
    /** A heat exchanger. */
    HeatExchanger: 'HeatExchanger',
    /** A power strip, typically placed in the zero-U space of a rack. */
    PowerStrip: 'PowerStrip',
    /** A chassis that does not fit any of these definitions. */
    Other: 'Other',
} as const;
