/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The enumerations of `HostingRole` specify different features that the hosting computer system supports.
 * @version 1.27.0
 */
export type ComputerSystemHostingRole =
    (typeof ComputerSystemHostingRole)[keyof typeof ComputerSystemHostingRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemHostingRole = {
    /** The system hosts functionality that supports general purpose applications. */
    ApplicationServer: 'ApplicationServer',
    /** The system hosts functionality that supports the system acting as a storage server. */
    StorageServer: 'StorageServer',
    /** The system hosts functionality that supports the system acting as a switch. */
    Switch: 'Switch',
    /** The system hosts functionality that supports the system acting as an appliance. */
    Appliance: 'Appliance',
    /** The system hosts functionality that supports the system acting as a bare-metal server. */
    BareMetalServer: 'BareMetalServer',
    /** The system hosts functionality that supports the system acting as a virtual machine server. */
    VirtualMachineServer: 'VirtualMachineServer',
    /** The system hosts functionality that supports the system acting as a container server. */
    ContainerServer: 'ContainerServer',
} as const;
