/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The idle power saver settings of a computer system.
 * @version 1.27.0
 */
export interface ComputerSystemIdlePowerSaver {
    /** An indication of whether idle power saver is enabled. */
    Enabled?: boolean;
    /**
     * The duration in seconds the computer system is below the `EnterUtilizationPercent` value before the idle power save is activated.
     * @minimum 0
     * @nullable
     */
    EnterDwellTimeSeconds?: number | null;
    /**
     * The percentage of utilization when the computer system enters idle power save.  If the computer system's utilization goes below this value, it enters idle power save.
     * @minimum 0
     * @nullable
     */
    EnterUtilizationPercent?: number | null;
    /**
     * The duration in seconds the computer system is above the `ExitUtilizationPercent` value before the idle power save is stopped.
     * @minimum 0
     * @nullable
     */
    ExitDwellTimeSeconds?: number | null;
    /**
     * The percentage of utilization when the computer system exits idle power save.  If the computer system's utilization goes above this value, it exits idle power save.
     * @minimum 0
     * @nullable
     */
    ExitUtilizationPercent?: number | null;
}
