/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { OdataV4Count } from './OdataV4Count';
import type { ResourceOem } from './ResourceOem';

/**
 * The links to other resources that are related to this resource.
 * @version 1.27.0
 */
export interface ComputerSystemLinks {
    /** An array of links to the chassis that contains this system. */
    readonly Chassis?: readonly OdataV4IdRef[];
    'Chassis@odata.count'?: OdataV4Count;
    /** An array of links to computer systems that are realized, in whole or in part, from this computer system. */
    readonly ConsumingComputerSystems?: readonly OdataV4IdRef[];
    'ConsumingComputerSystems@odata.count'?: OdataV4Count;
    /** An array of links to resources or objects that cool this computer system.  Normally, the link is for either a chassis or a specific set of fans. */
    readonly CooledBy?: readonly OdataV4IdRef[];
    'CooledBy@odata.count'?: OdataV4Count;
    /** An array of links to the endpoints that connect to this system. */
    readonly Endpoints?: readonly OdataV4IdRef[];
    'Endpoints@odata.count'?: OdataV4Count;
    /**
     * The link to the system that is hosting this virtual machine.
     * @nullable
     */
    readonly HostingComputerSystem?: OdataV4IdRef;
    /** An array of links to the managers responsible for this system. */
    readonly ManagedBy?: readonly OdataV4IdRef[];
    'ManagedBy@odata.count'?: OdataV4Count;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** The network device functions to which this system performs offload computation, such as with a SmartNIC. */
    readonly OffloadedNetworkDeviceFunctions?: readonly OdataV4IdRef[];
    'OffloadedNetworkDeviceFunctions@odata.count'?: OdataV4Count;
    /** An array of links to resources or objects that power this computer system.  Normally, the link is for either a chassis or a specific set of power supplies. */
    readonly PoweredBy?: readonly OdataV4IdRef[];
    'PoweredBy@odata.count'?: OdataV4Count;
    /** An array of links to the resource blocks that are used in this computer system. */
    ResourceBlocks?: OdataV4IdRef[];
    'ResourceBlocks@odata.count'?: OdataV4Count;
    /** An array of links to computer systems that contribute, in whole or in part, to the implementation of this computer system. */
    readonly SupplyingComputerSystems?: readonly OdataV4IdRef[];
    'SupplyingComputerSystems@odata.count'?: OdataV4Count;
    /** An array of links to the trusted components for this system. */
    readonly TrustedComponents?: readonly OdataV4IdRef[];
    'TrustedComponents@odata.count'?: OdataV4Count;
    /** An array of links to the virtual machines this system is hosting. */
    readonly VirtualMachines?: readonly OdataV4IdRef[];
    'VirtualMachines@odata.count'?: OdataV4Count;
}
