/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceResetType } from './ResourceResetType';

/**
 * This action resets the system.
 * @version 1.27.0
 */
export interface ComputerSystemResetRequestBody {
    /** The type of reset. */
    ResetType?: ResourceResetType;
}
