/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.27.0
 */
export type ComputerSystemInterfaceType =
    (typeof ComputerSystemInterfaceType)[keyof typeof ComputerSystemInterfaceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemInterfaceType = {
    /** Trusted Platform Module (TPM) 1.2. */
    TPM1_2: 'TPM1_2',
    /** Trusted Platform Module (TPM) 2.0. */
    TPM2_0: 'TPM2_0',
    /** Trusted Cryptography Module (TCM) 1.0. */
    TCM1_0: 'TCM1_0',
} as const;
