/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * This action removes a resource block from a system.
 * @version 1.27.0
 */
export interface ComputerSystemRemoveResourceBlock {
    /** Link to invoke action */
    target?: string;
    /** Friendly action name */
    title?: string;
}
