/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.27.0
 */
export type ComputerSystemGraphicalConnectTypesSupported =
    (typeof ComputerSystemGraphicalConnectTypesSupported)[keyof typeof ComputerSystemGraphicalConnectTypesSupported];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemGraphicalConnectTypesSupported = {
    /** The controller supports a graphical console connection through a KVM-IP (redirection of Keyboard, Video, Mouse over IP) protocol. */
    KVMIP: 'KVMIP',
    /** The controller supports a graphical console connection through an OEM-specific protocol. */
    OEM: 'OEM',
} as const;
