/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.27.0
 */
export type ComputerSystemBootSourceOverrideEnabled =
    (typeof ComputerSystemBootSourceOverrideEnabled)[keyof typeof ComputerSystemBootSourceOverrideEnabled];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemBootSourceOverrideEnabled = {
    /** The system boots normally. */
    Disabled: 'Disabled',
    /** On its next boot cycle, the system boots one time to the boot source override target.  Then, the `BootSourceOverrideEnabled` value is reset to `Disabled`. */
    Once: 'Once',
    /** The system boots to the target specified in the `BootSourceOverrideTarget` property until this property is `Disabled`. */
    Continuous: 'Continuous',
} as const;
