/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ComputerSystemSerialConsoleProtocol } from './ComputerSystemSerialConsoleProtocol';
import type { ComputerSystemWebSocketConsole } from './ComputerSystemWebSocketConsole';

/**
 * The information about the serial console services that this system provides.
 * @version 1.27.0
 */
export interface ComputerSystemHostSerialConsole {
    /** The connection details for an IPMI Serial-over-LAN service. */
    IPMI?: ComputerSystemSerialConsoleProtocol;
    /**
     * The maximum number of service sessions, regardless of protocol, that this system can support.
     * @minimum 0
     */
    readonly MaxConcurrentSessions?: number;
    /** The connection details for an SSH serial console service. */
    SSH?: ComputerSystemSerialConsoleProtocol;
    /** The connection details for a Telnet serial console service. */
    Telnet?: ComputerSystemSerialConsoleProtocol;
    /** The connection details for a WebSocket serial console service. */
    WebSocket?: ComputerSystemWebSocketConsole;
}
