/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.27.0
 */
export type ComputerSystemStopBootOnFault =
    (typeof ComputerSystemStopBootOnFault)[keyof typeof ComputerSystemStopBootOnFault];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemStopBootOnFault = {
    /** The system performs any normal recovery actions during boot if a fault occurs. */
    Never: 'Never',
    /** The system should stop the boot on any fault. */
    AnyFault: 'AnyFault',
} as const;
