/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.27.0
 */
export type ComputerSystemLastResetCauses =
    (typeof ComputerSystemLastResetCauses)[keyof typeof ComputerSystemLastResetCauses];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemLastResetCauses = {
    /** System start or restart via a power button press. */
    PowerButtonPress: 'PowerButtonPress',
    /** System start or restart via an external command to the management controller or BMC. */
    ManagementCommand: 'ManagementCommand',
    /** System start or restart due to the power restore policy. */
    PowerRestorePolicy: 'PowerRestorePolicy',
    /** System power-up via an RTC (system real time clock) wakeup. */
    RTCWakeup: 'RTCWakeup',
    /** System start or restart caused by a watchdog expiration. */
    WatchdogExpiration: 'WatchdogExpiration',
    /** System start or restart via an OS soft restart. */
    OSSoftRestart: 'OSSoftRestart',
    /** System start or restart caused by a system crash. */
    SystemCrash: 'SystemCrash',
    /** System start or restart caused by a thermal event triggering a system shutdown. */
    ThermalEvent: 'ThermalEvent',
    /** System start or restart caused by a power event triggering a system shutdown. */
    PowerEvent: 'PowerEvent',
    /** System start or restart detected, but the cause is unknown. */
    Unknown: 'Unknown',
} as const;
