/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The information about the in-band IPMI service for this system.
 * @version 1.27.0
 */
export interface ComputerSystemIPMIHostInterface {
    /** An indication of whether the service is enabled for this system. */
    ServiceEnabled?: boolean;
}
