/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { ResourceStatus } from './ResourceStatus';

/**
 * The central processors of the system in general detail.
 * @version 1.27.0
 */
export interface ComputerSystemProcessorSummary {
    /**
     * The number of processor cores in the system.
     * @minimum 0
     * @nullable
     */
    readonly CoreCount?: number | null;
    /**
     * The number of physical processors in the system.
     * @minimum 0
     * @nullable
     */
    readonly Count?: number | null;
    /**
     * The number of logical processors in the system.
     * @minimum 0
     * @nullable
     */
    readonly LogicalProcessorCount?: number | null;
    /** The link to the metrics associated with all processors in this system. */
    readonly Metrics?: OdataV4IdRef;
    /**
     * The processor model for the primary or majority of processors in this system.
     * @nullable
     */
    readonly Model?: string | null;
    /**
     * The status and health of the resource and its subordinate or dependent resources.
     * @deprecated
     */
    Status?: ResourceStatus;
    /** An indication of whether threading is enabled on all processors in this system. */
    ThreadingEnabled?: boolean;
}
