/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.27.0
 */
export type ComputerSystemBootProgressTypes =
    (typeof ComputerSystemBootProgressTypes)[keyof typeof ComputerSystemBootProgressTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemBootProgressTypes = {
    /** The system is not booting. */
    None: 'None',
    /** The system has started initializing the primary processor. */
    PrimaryProcessorInitializationStarted:
        'PrimaryProcessorInitializationStarted',
    /** The system has started initializing the buses. */
    BusInitializationStarted: 'BusInitializationStarted',
    /** The system has started initializing the memory. */
    MemoryInitializationStarted: 'MemoryInitializationStarted',
    /** The system has started initializing the remaining processors. */
    SecondaryProcessorInitializationStarted:
        'SecondaryProcessorInitializationStarted',
    /** The system has started initializing the PCI resources. */
    PCIResourceConfigStarted: 'PCIResourceConfigStarted',
    /** The system has completed initializing all hardware. */
    SystemHardwareInitializationComplete:
        'SystemHardwareInitializationComplete',
    /** The system has entered the setup utility. */
    SetupEntered: 'SetupEntered',
    /** The operating system has started booting. */
    OSBootStarted: 'OSBootStarted',
    /** The operating system is running. */
    OSRunning: 'OSRunning',
    /** A boot progress state in an OEM-defined format. */
    OEM: 'OEM',
} as const;
