/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The enumerations of `WatchdogWarningActions` specify the choice of action to take when the host watchdog timer is close (typically 3-10 seconds) to reaching its timeout value.
 * @version 1.27.0
 */
export type ComputerSystemWatchdogWarningActions =
    (typeof ComputerSystemWatchdogWarningActions)[keyof typeof ComputerSystemWatchdogWarningActions];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemWatchdogWarningActions = {
    /** No action taken. */
    None: 'None',
    /** Raise a (typically non-maskable) Diagnostic Interrupt. */
    DiagnosticInterrupt: 'DiagnosticInterrupt',
    /** Raise a Systems Management Interrupt (SMI). */
    SMI: 'SMI',
    /** Raise a legacy IPMI messaging interrupt. */
    MessagingInterrupt: 'MessagingInterrupt',
    /** Raise an interrupt using the ACPI System Control Interrupt (SCI). */
    SCI: 'SCI',
    /** Perform an OEM-defined action. */
    OEM: 'OEM',
} as const;
