/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ComputerSystemAddResourceBlock } from './ComputerSystemAddResourceBlock';
import type { ComputerSystemDecommission } from './ComputerSystemDecommission';
import type { ComputerSystemExportConfiguration } from './ComputerSystemExportConfiguration';
import type { ComputerSystemRemoveResourceBlock } from './ComputerSystemRemoveResourceBlock';
import type { ComputerSystemReset } from './ComputerSystemReset';
import type { ComputerSystemSetDefaultBootOrder } from './ComputerSystemSetDefaultBootOrder';
import type { ComputerSystemOemActions } from './ComputerSystemOemActions';

/**
 * The available actions for this resource.
 * @version 1.27.0
 */
export interface ComputerSystemActions {
    '#ComputerSystem.AddResourceBlock'?: ComputerSystemAddResourceBlock;
    '#ComputerSystem.Decommission'?: ComputerSystemDecommission;
    '#ComputerSystem.ExportConfiguration'?: ComputerSystemExportConfiguration;
    '#ComputerSystem.RemoveResourceBlock'?: ComputerSystemRemoveResourceBlock;
    '#ComputerSystem.Reset'?: ComputerSystemReset;
    '#ComputerSystem.SetDefaultBootOrder'?: ComputerSystemSetDefaultBootOrder;
    /** The available OEM-specific actions for this resource. */
    Oem?: ComputerSystemOemActions;
}
