/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ComputerSystemKMIPCachePolicy } from './ComputerSystemKMIPCachePolicy';

/**
 * The KMIP server settings for a computer system.
 * @version 1.27.0
 */
export interface ComputerSystemKMIPServer {
    /**
     * The KMIP server address.
     * @nullable
     */
    Address?: string | null;
    /**
     * The duration the system caches KMIP data.
     * @nullable
     * @pattern ^P(\d+D)?(T(\d+H)?(\d+M)?(\d+(.\d+)?S)?)?$
     */
    CacheDuration?: string | null;
    /**
     * The cache policy to control how KMIP data is cached.
     * @nullable
     */
    CachePolicy?: ComputerSystemKMIPCachePolicy;
    /**
     * The password to access the KMIP server.  The value is `null` in responses.
     * @nullable
     */
    Password?: string | null;
    /**
     * The KMIP server port.
     * @nullable
     */
    Port?: number | null;
    /**
     * The username to access the KMIP server.
     * @nullable
     */
    Username?: string | null;
}
