/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The information about a WebSocket serial console service that this system provides.
 * @version 1.27.0
 */
export interface ComputerSystemWebSocketConsole {
    /** The URI at which to access the WebSocket serial console. */
    readonly ConsoleURI?: string;
    /** Indicates if the WebSocket serial console allows interactive input. */
    readonly Interactive?: boolean;
    /** An indication of whether the service is enabled for this system. */
    ServiceEnabled?: boolean;
}
