/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceOem } from './ResourceOem';
import type { OdataV4IdRef } from './OdataV4IdRef';

/**
 * The services that might be running or installed on the system.
 * @version 1.27.0
 */
export interface ComputerSystemHostedServices {
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** The link to a collection of storage services that this computer system supports. */
    readonly StorageServices?: OdataV4IdRef;
}
