/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.27.0
 */
export type ComputerSystemKMIPCachePolicy =
    (typeof ComputerSystemKMIPCachePolicy)[keyof typeof ComputerSystemKMIPCachePolicy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemKMIPCachePolicy = {
    /** The system does not cache KMIP data. */
    None: 'None',
    /** The system caches KMIP data after first use for the duration specified by the `CacheDuration` property. */
    AfterFirstUse: 'AfterFirstUse',
} as const;
