/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The information about a serial console service that this system provides.
 * @version 1.27.0
 */
export interface ComputerSystemSerialConsoleProtocol {
    /**
     * The command string passed to the service to select or enter the system's serial console.
     * @nullable
     */
    readonly ConsoleEntryCommand?: string | null;
    /**
     * The hotkey sequence available for the user to exit the serial console session.
     * @nullable
     */
    readonly HotKeySequenceDisplay?: string | null;
    /**
     * The protocol port.
     * @minimum 0
     * @nullable
     */
    Port?: number | null;
    /** An indication of whether the service is enabled for this system. */
    ServiceEnabled?: boolean;
    /** Indicates whether the serial console service is shared with access to the manager's command-line interface (CLI). */
    readonly SharedWithManagerCLI?: boolean;
}
