/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ComputerSystemBootProgressTypes } from './ComputerSystemBootProgressTypes';
import type { ResourceOem } from './ResourceOem';

/**
 * This object describes the last boot progress state.
 * @version 1.27.0
 */
export interface ComputerSystemBootProgress {
    /**
     * The number of seconds the system spent booting to the operating system during the last boot.
     * @nullable
     */
    readonly LastBootTimeSeconds?: number | null;
    /**
     * The last boot progress state.
     * @nullable
     */
    readonly LastState?: ComputerSystemBootProgressTypes;
    /**
     * The date and time when the last boot state was updated.
     * @nullable
     */
    readonly LastStateTime?: string | null;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * The OEM-specific last state, if the LastState type is `OEM`.
     * @nullable
     */
    readonly OemLastState?: string | null;
}
