/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The enumerations of `InterfaceTypeSelection` specify the method for switching the TrustedModule InterfaceType, for instance between TPM1_2 and TPM2_0, if supported.
 * @version 1.27.0
 */
export type ComputerSystemInterfaceTypeSelection =
    (typeof ComputerSystemInterfaceTypeSelection)[keyof typeof ComputerSystemInterfaceTypeSelection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemInterfaceTypeSelection = {
    /** The TrustedModule does not support switching the InterfaceType. */
    None: 'None',
    /** The TrustedModule supports switching InterfaceType through a firmware update. */
    FirmwareUpdate: 'FirmwareUpdate',
    /** The TrustedModule supports switching InterfaceType through platform software, such as a BIOS configuration attribute. */
    BiosSetting: 'BiosSetting',
    /** The TrustedModule supports switching InterfaceType through an OEM proprietary mechanism. */
    OemMethod: 'OemMethod',
} as const;
