/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.27.0
 */
export type ComputerSystemAutomaticRetryConfig =
    (typeof ComputerSystemAutomaticRetryConfig)[keyof typeof ComputerSystemAutomaticRetryConfig];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemAutomaticRetryConfig = {
    /** Disable automatic retrying of booting. */
    Disabled: 'Disabled',
    /** Automatic retrying of booting is based on a specified retry count. */
    RetryAttempts: 'RetryAttempts',
    /** Always automatically retry booting. */
    RetryAlways: 'RetryAlways',
} as const;
