/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The enumerations of `BootOrderTypes` specify the choice of boot order property to use when controller the persistent boot order for this computer system.
 * @version 1.27.0
 */
export type ComputerSystemBootOrderTypes =
    (typeof ComputerSystemBootOrderTypes)[keyof typeof ComputerSystemBootOrderTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemBootOrderTypes = {
    /** The system uses the `BootOrder` property to specify the persistent boot order. */
    BootOrder: 'BootOrder',
    /** The system uses the `AliasBootOrder` property to specify the persistent boot order. */
    AliasBootOrder: 'AliasBootOrder',
} as const;
