/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.27.0
 */
export type ComputerSystemBootSourceOverrideMode =
    (typeof ComputerSystemBootSourceOverrideMode)[keyof typeof ComputerSystemBootSourceOverrideMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemBootSourceOverrideMode = {
    /** The system boots in non-UEFI boot mode to the boot source override target. */
    Legacy: 'Legacy',
    /** The system boots in UEFI boot mode to the boot source override target. */
    UEFI: 'UEFI',
} as const;
