/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.27.0
 */
export type ComputerSystemCompositionUseCase =
    (typeof ComputerSystemCompositionUseCase)[keyof typeof ComputerSystemCompositionUseCase];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemCompositionUseCase = {
    /** This computer system supports being registered as a resource block in order for it to participate in composition requests. */
    ResourceBlockCapable: 'ResourceBlockCapable',
    /** This computer system supports expandable system composition and is associated with a resource block. */
    ExpandableSystem: 'ExpandableSystem',
} as const;
