/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ComputerSystemInterfaceType } from './ComputerSystemInterfaceType';
import type { ComputerSystemInterfaceTypeSelection } from './ComputerSystemInterfaceTypeSelection';
import type { ResourceOem } from './ResourceOem';
import type { ResourceStatus } from './ResourceStatus';

/**
 * The Trusted Module installed in the system.
 * @version 1.27.0
 */
export interface ComputerSystemTrustedModules {
    /**
     * The firmware version of this Trusted Module.
     * @nullable
     */
    readonly FirmwareVersion?: string | null;
    /**
     * The second firmware version of this Trusted Module, if applicable.
     * @nullable
     */
    readonly FirmwareVersion2?: string | null;
    /**
     * The interface type of the Trusted Module.
     * @nullable
     */
    readonly InterfaceType?: ComputerSystemInterfaceType;
    /**
     * The interface type selection supported by this Trusted Module.
     * @nullable
     */
    readonly InterfaceTypeSelection?: ComputerSystemInterfaceTypeSelection;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** The status and health of the resource and its subordinate or dependent resources. */
    Status?: ResourceStatus;
}
