/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.27.0
 */
export type ComputerSystemIndicatorLED =
    (typeof ComputerSystemIndicatorLED)[keyof typeof ComputerSystemIndicatorLED];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemIndicatorLED = {
    /** The state of the indicator LED cannot be determined. */
    Unknown: 'Unknown',
    /** The indicator LED is lit. */
    Lit: 'Lit',
    /** The indicator LED is blinking. */
    Blinking: 'Blinking',
    /** The indicator LED is off. */
    Off: 'Off',
} as const;
