/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

export type ComputerSystemBootSource =
    (typeof ComputerSystemBootSource)[keyof typeof ComputerSystemBootSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemBootSource = {
    /** Boot from the normal boot device. */
    None: 'None',
    /** Boot from the Pre-boot eXecution Environment (PXE). */
    Pxe: 'Pxe',
    /** Boot from the floppy disk drive. */
    Floppy: 'Floppy',
    /** Boot from the CD or DVD. */
    Cd: 'Cd',
    /** Boot from a system BIOS-specified USB device. */
    Usb: 'Usb',
    /** Boot from a hard drive. */
    Hdd: 'Hdd',
    /** Boot to the BIOS setup utility. */
    BiosSetup: 'BiosSetup',
    /** Boot to the manufacturer\'s utilities program or programs. */
    Utilities: 'Utilities',
    /** Boot to the manufacturer\'s diagnostics program. */
    Diags: 'Diags',
    /** Boot to the UEFI Shell. */
    UefiShell: 'UefiShell',
    /** Boot to the UEFI device specified in the `UefiTargetBootSourceOverride` property. */
    UefiTarget: 'UefiTarget',
    /** Boot from an SD card. */
    SDCard: 'SDCard',
    /** Boot from a UEFI HTTP network location. */
    UefiHttp: 'UefiHttp',
    /** Boot from a remote drive, such as an iSCSI target. */
    RemoteDrive: 'RemoteDrive',
    /** Boot to the UEFI device that the `BootNext` property specifies. */
    UefiBootNext: 'UefiBootNext',
    /** Boot to a system-designated recovery process or image. */
    Recovery: 'Recovery',
} as const;
