/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ComputerSystemMemoryMirroring } from './ComputerSystemMemoryMirroring';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { ResourceStatus } from './ResourceStatus';

/**
 * The memory of the system in general detail.
 * @version 1.27.0
 */
export interface ComputerSystemMemorySummary {
    /**
     * The ability and type of memory mirroring that this computer system supports.
     * @nullable
     */
    readonly MemoryMirroring?: ComputerSystemMemoryMirroring;
    /** The link to the metrics associated with all memory in this system. */
    readonly Metrics?: OdataV4IdRef;
    /**
     * The status and health of the resource and its subordinate or dependent resources.
     * @deprecated
     */
    Status?: ResourceStatus;
    /**
     * The total configured operating system-accessible memory (RAM), measured in GiB.
     * @minimum 0
     * @nullable
     */
    readonly TotalSystemMemoryGiB?: number | null;
    /**
     * The total configured, system-accessible persistent memory, measured in GiB.
     * @minimum 0
     * @nullable
     */
    readonly TotalSystemPersistentMemoryGiB?: number | null;
}
