/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceOem } from './ResourceOem';
import type { ResourceStatus } from './ResourceStatus';
import type { ComputerSystemWatchdogTimeoutActions } from './ComputerSystemWatchdogTimeoutActions';
import type { ComputerSystemWatchdogWarningActions } from './ComputerSystemWatchdogWarningActions';

/**
 * This type describes the host watchdog timer functionality for this system.
 * @version 1.27.0
 */
export interface ComputerSystemWatchdogTimer {
    /**
     * An indication of whether a user has enabled the host watchdog timer functionality.  This property indicates only that a user has enabled the timer.  To activate the timer, installation of additional host-based software is necessary; an update to this property does not initiate the timer.
     * @nullable
     */
    FunctionEnabled: boolean | null;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** The status and health of the resource and its subordinate or dependent resources. */
    Status?: ResourceStatus;
    /**
     * The action to perform when the watchdog timer reaches its timeout value.
     * @nullable
     */
    TimeoutAction: ComputerSystemWatchdogTimeoutActions;
    /**
     * The action to perform when the watchdog timer is close to reaching its timeout value.  This action typically occurs from three to ten seconds before to the timeout value, but the exact timing is dependent on the implementation.
     * @nullable
     */
    WarningAction?: ComputerSystemWatchdogWarningActions;
}
