/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.27.0
 */
export type ComputerSystemMemoryMirroring =
    (typeof ComputerSystemMemoryMirroring)[keyof typeof ComputerSystemMemoryMirroring];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemMemoryMirroring = {
    /** The system supports DIMM mirroring at the system level.  Individual DIMMs are not paired for mirroring in this mode. */
    System: 'System',
    /** The system supports DIMM mirroring at the DIMM level.  Individual DIMMs can be mirrored. */
    DIMM: 'DIMM',
    /** The system supports a hybrid mirroring at the system and DIMM levels.  Individual DIMMs can be mirrored. */
    Hybrid: 'Hybrid',
    /** The system does not support DIMM mirroring. */
    None: 'None',
} as const;
