/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { ComputerSystemKMIPServer } from './ComputerSystemKMIPServer';

/**
 * The key management settings of a computer system.
 * @version 1.27.0
 */
export interface ComputerSystemKeyManagement {
    /** The link to a collection of server certificates for the servers referenced by the `KMIPServers` property. */
    readonly KMIPCertificates?: OdataV4IdRef;
    /** The link to a collection of client identity certificates provided to the servers referenced by the `KMIPServers` property. */
    readonly KMIPClientCertificates?: OdataV4IdRef;
    /** The KMIP servers to which this computer system is subscribed. */
    KMIPServers?: ComputerSystemKMIPServer[];
}
