/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.27.0
 */
export type ComputerSystemPowerMode =
    (typeof ComputerSystemPowerMode)[keyof typeof ComputerSystemPowerMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemPowerMode = {
    /** The system performs at the highest speeds possible. */
    MaximumPerformance: 'MaximumPerformance',
    /** The system performs at the highest speeds while utilization is high and performs at reduced speeds when the utilization is low. */
    BalancedPerformance: 'BalancedPerformance',
    /** The system performs at reduced speeds to save power. */
    PowerSaving: 'PowerSaving',
    /** The system power mode is static. */
    Static: 'Static',
    /** The system power mode is controlled by the operating system. */
    OSControlled: 'OSControlled',
    /** The system power mode is OEM-defined. */
    OEM: 'OEM',
    /** The system performs at reduced speeds at all utilizations to save power at the cost of performance.  This mode differs from `PowerSaving` in that more performance is retained and less power is saved.  This mode differs from `EfficiencyFavorPerformance` in that less performance is retained but more power is saved. */
    EfficiencyFavorPower: 'EfficiencyFavorPower',
    /** The system performs at reduced speeds at all utilizations to save power while attempting to maintain performance.  This mode differs from `EfficiencyFavorPower` in that more performance is retained but less power is saved. */
    EfficiencyFavorPerformance: 'EfficiencyFavorPerformance',
} as const;
