/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ComputerSystemBootSource } from './ComputerSystemBootSource';
import type { ComputerSystemAutomaticRetryConfig } from './ComputerSystemAutomaticRetryConfig';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { ComputerSystemBootOrderTypes } from './ComputerSystemBootOrderTypes';
import type { ComputerSystemBootSourceOverrideEnabled } from './ComputerSystemBootSourceOverrideEnabled';
import type { ComputerSystemBootSourceOverrideMode } from './ComputerSystemBootSourceOverrideMode';
import type { ComputerSystemStopBootOnFault } from './ComputerSystemStopBootOnFault';
import type { ComputerSystemTrustedModuleRequiredToBoot } from './ComputerSystemTrustedModuleRequiredToBoot';

/**
 * The boot information for this resource.
 * @version 1.27.0
 */
export interface ComputerSystemBoot {
    /** Ordered array of boot source aliases representing the persistent boot order associated with this computer system. */
    AliasBootOrder?: ComputerSystemBootSource[];
    /**
     * The number of attempts the system will automatically retry booting.
     * @minimum 0
     * @nullable
     */
    AutomaticRetryAttempts?: number | null;
    /**
     * The configuration of how the system retries booting automatically.
     * @nullable
     */
    AutomaticRetryConfig?: ComputerSystemAutomaticRetryConfig;
    /**
     * The `BootOptionReference` of the Boot Option to perform a one-time boot from when `BootSourceOverrideTarget` is `UefiBootNext`.
     * @nullable
     */
    BootNext?: string | null;
    /** The link to the collection of the UEFI boot options associated with this computer system. */
    readonly BootOptions?: OdataV4IdRef;
    /** An array of `BootOptionReference` strings that represent the persistent boot order for with this computer system.  Changes to the boot order typically require a system reset before they take effect.  It is likely that a client finds the `@Redfish.Settings` term in this resource, and if it is found, the client makes requests to change boot order settings by modifying the resource identified by the `@Redfish.Settings` term. */
    BootOrder?: (string | null)[];
    /**
     * The name of the boot order property that the system uses for the persistent boot order.
     * @nullable
     */
    BootOrderPropertySelection?: ComputerSystemBootOrderTypes;
    /**
     * The state of the boot source override feature.
     * @nullable
     */
    BootSourceOverrideEnabled?: ComputerSystemBootSourceOverrideEnabled;
    /**
     * The BIOS boot mode to use when the system boots from the `BootSourceOverrideTarget` boot source.
     * @nullable
     */
    BootSourceOverrideMode?: ComputerSystemBootSourceOverrideMode;
    /**
     * The current boot source to use at the next boot instead of the normal boot device, if `BootSourceOverrideEnabled` does not contain `Disabled`.
     * @nullable
     */
    BootSourceOverrideTarget?: ComputerSystemBootSource;
    /** The link to a collection of certificates used for booting through HTTPS by this computer system. */
    readonly Certificates?: OdataV4IdRef;
    /**
     * The URI to boot from when `BootSourceOverrideTarget` is set to `UefiHttp`.
     * @nullable
     */
    HttpBootUri?: string | null;
    /**
     * The number of remaining automatic retry boots.
     * @minimum 0
     * @nullable
     */
    readonly RemainingAutomaticRetryAttempts?: number | null;
    /**
     * If the boot should stop on a fault.
     * @nullable
     */
    StopBootOnFault?: ComputerSystemStopBootOnFault;
    /**
     * The Trusted Module boot requirement.
     * @nullable
     */
    TrustedModuleRequiredToBoot?: ComputerSystemTrustedModuleRequiredToBoot;
    /**
     * The UEFI device path of the device from which to boot when `BootSourceOverrideTarget` is `UefiTarget`.
     * @nullable
     */
    UefiTargetBootSourceOverride?: string | null;
}
