/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The enumerations of `PowerRestorePolicyTypes` specify the choice of power state for the system when power is applied.
 * @version 1.27.0
 */
export type ComputerSystemPowerRestorePolicyTypes =
    (typeof ComputerSystemPowerRestorePolicyTypes)[keyof typeof ComputerSystemPowerRestorePolicyTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemPowerRestorePolicyTypes = {
    /** The system always powers on when power is applied. */
    AlwaysOn: 'AlwaysOn',
    /** The system always remains powered off when power is applied. */
    AlwaysOff: 'AlwaysOff',
    /** The system returns to its last on or off power state when power is applied. */
    LastState: 'LastState',
} as const;
