/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The information about virtual media service for this system.
 * @version 1.27.0
 */
export interface ComputerSystemVirtualMediaConfig {
    /**
     * The protocol port.
     * @minimum 0
     * @nullable
     */
    Port?: number | null;
    /** An indication of whether the service is enabled for this system. */
    ServiceEnabled?: boolean;
}
