/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The enumerations of `WatchdogTimeoutActions` specify the choice of action to take when the host watchdog timer reaches its timeout value.
 * @version 1.27.0
 */
export type ComputerSystemWatchdogTimeoutActions =
    (typeof ComputerSystemWatchdogTimeoutActions)[keyof typeof ComputerSystemWatchdogTimeoutActions];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemWatchdogTimeoutActions = {
    /** No action taken. */
    None: 'None',
    /** Reset the system. */
    ResetSystem: 'ResetSystem',
    /** Power cycle the system. */
    PowerCycle: 'PowerCycle',
    /** Power down the system. */
    PowerDown: 'PowerDown',
    /** Perform an OEM-defined action. */
    OEM: 'OEM',
} as const;
