/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Context } from './OdataV4Context';
import type { OdataV4Etag } from './OdataV4Etag';
import type { OdataV4Id } from './OdataV4Id';
import type { OdataV4Type } from './OdataV4Type';
import type { ComputerSystemActions } from './ComputerSystemActions';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { ComputerSystemBoot } from './ComputerSystemBoot';
import type { ComputerSystemBootProgress } from './ComputerSystemBootProgress';
import type { ComputerSystemComposition } from './ComputerSystemComposition';
import type { ResourceDescription } from './ResourceDescription';
import type { ComputerSystemHostGraphicalConsole } from './ComputerSystemHostGraphicalConsole';
import type { ComputerSystemWatchdogTimer } from './ComputerSystemWatchdogTimer';
import type { ComputerSystemHostedServices } from './ComputerSystemHostedServices';
import type { ComputerSystemHostingRole } from './ComputerSystemHostingRole';
import type { ComputerSystemIPMIHostInterface } from './ComputerSystemIPMIHostInterface';
import type { ResourceId } from './ResourceId';
import type { ComputerSystemIdlePowerSaver } from './ComputerSystemIdlePowerSaver';
import type { ComputerSystemIndicatorLED } from './ComputerSystemIndicatorLED';
import type { ComputerSystemKeyManagement } from './ComputerSystemKeyManagement';
import type { ComputerSystemLastResetCauses } from './ComputerSystemLastResetCauses';
import type { ComputerSystemLinks } from './ComputerSystemLinks';
import type { SoftwareInventoryMeasurementBlock } from './SoftwareInventoryMeasurementBlock';
import type { ComputerSystemMemorySummary } from './ComputerSystemMemorySummary';
import type { ResourceName } from './ResourceName';
import type { ResourceOem } from './ResourceOem';
import type { OdataV4Count } from './OdataV4Count';
import type { ComputerSystemPowerMode } from './ComputerSystemPowerMode';
import type { ComputerSystemPowerRestorePolicyTypes } from './ComputerSystemPowerRestorePolicyTypes';
import type { ResourcePowerState } from './ResourcePowerState';
import type { ComputerSystemProcessorSummary } from './ComputerSystemProcessorSummary';
import type { Redundancy } from './Redundancy';
import type { ComputerSystemHostSerialConsole } from './ComputerSystemHostSerialConsole';
import type { ResourceStatus } from './ResourceStatus';
import type { ComputerSystemSystemType } from './ComputerSystemSystemType';
import type { ComputerSystemTrustedModules } from './ComputerSystemTrustedModules';
import type { ResourceUUID } from './ResourceUUID';
import type { ComputerSystemVirtualMediaConfig } from './ComputerSystemVirtualMediaConfig';

/**
 * The `ComputerSystem` schema represents a computer or system instance and the software-visible resources, or items within the data plane, such as memory, CPU, and other devices that it can access.  Details of those resources or subsystems are also linked through this resource.
 * @version 1.27.0
 */
export interface ComputerSystem {
    '@odata.context'?: OdataV4Context;
    '@odata.etag'?: OdataV4Etag;
    '@odata.id': OdataV4Id;
    '@odata.type': OdataV4Type;
    /** The available actions for this resource. */
    Actions?: ComputerSystemActions;
    /**
     * The user-definable tag that can track this computer system for inventory or other client purposes.
     * @nullable
     */
    AssetTag?: string | null;
    /** The link to the BIOS settings associated with this system. */
    readonly Bios?: OdataV4IdRef;
    /**
     * The version of the system BIOS or primary system firmware.
     * @nullable
     */
    readonly BiosVersion?: string | null;
    /** The boot settings for this system. */
    Boot?: ComputerSystemBoot;
    /**
     * This object describes the last boot progress state.
     * @nullable
     */
    BootProgress?: ComputerSystemBootProgress;
    /** The link to a collection of certificates for device identity and attestation. */
    readonly Certificates?: OdataV4IdRef;
    /**
     * Information about the composition capabilities and state of the computer system.
     * @nullable
     */
    Composition?: ComputerSystemComposition;
    /** @nullable */
    readonly Description?: ResourceDescription;
    /** The link to the collection of Ethernet interfaces associated with this system. */
    readonly EthernetInterfaces?: OdataV4IdRef;
    /** The link to the collection of fabric adapters associated with this system. */
    readonly FabricAdapters?: OdataV4IdRef;
    /** The information about the graphical console (KVM-IP) service of this system. */
    GraphicalConsole?: ComputerSystemHostGraphicalConsole;
    /** The link to a collection of graphics controllers that can output video for this system. */
    readonly GraphicsControllers?: OdataV4IdRef;
    /**
     * The DNS host name, without any domain information.
     * @nullable
     */
    HostName?: string | null;
    /** The host watchdog timer functionality for this system. */
    HostWatchdogTimer?: ComputerSystemWatchdogTimer;
    /** The services that this computer system supports. */
    HostedServices?: ComputerSystemHostedServices;
    /** The hosting roles that this computer system supports. */
    readonly HostingRoles?: readonly ComputerSystemHostingRole[];
    /** The information about the in-band IPMI service of this system. */
    IPMIHostInterface?: ComputerSystemIPMIHostInterface;
    readonly Id: ResourceId;
    /**
     * The idle power saver settings of the computer system.
     * @nullable
     */
    IdlePowerSaver?: ComputerSystemIdlePowerSaver;
    /**
     * The state of the indicator LED, which identifies the system.
     * @deprecated
     * @nullable
     */
    IndicatorLED?: ComputerSystemIndicatorLED;
    /**
     * The key management settings of the computer system.
     * @nullable
     */
    KeyManagement?: ComputerSystemKeyManagement;
    /** The last reset cause of the system. */
    readonly LastResetCause?: ComputerSystemLastResetCauses;
    /** The date and time when the system was last reset or rebooted. */
    readonly LastResetTime?: string;
    /** The links to other resources that are related to this resource. */
    Links?: ComputerSystemLinks;
    /**
     * An indicator allowing an operator to physically locate this resource.
     * @nullable
     */
    LocationIndicatorActive?: boolean | null;
    /** The link to the collection of log services associated with this system. */
    readonly LogServices?: OdataV4IdRef;
    /**
     * The manufacturer or OEM of this system.
     * @nullable
     */
    readonly Manufacturer?: string | null;
    /**
     * An indication of whether the system is in manufacturing mode.  Manufacturing mode is a special boot mode, not normally available to end users, that modifies features and settings for use while the system is being manufactured and tested.
     * @nullable
     */
    readonly ManufacturingMode?: boolean | null;
    /**
     * An array of DSP0274-defined measurement blocks.
     * @deprecated
     */
    Measurements?: SoftwareInventoryMeasurementBlock[];
    /** The link to the collection of memory associated with this system. */
    readonly Memory?: OdataV4IdRef;
    /** The link to the collection of memory domains associated with this system. */
    readonly MemoryDomains?: OdataV4IdRef;
    /** The central memory of the system in general detail. */
    MemorySummary?: ComputerSystemMemorySummary;
    /**
     * The product name for this system, without the manufacturer name.
     * @nullable
     */
    readonly Model?: string | null;
    /** The URI used to perform a Redfish Specification-defined multipart HTTP or HTTPS push import of a vendor-specific configuration file. */
    readonly MultipartImportConfigurationPushURI?: string;
    readonly Name: ResourceName;
    /** The link to the collection of Network Interfaces associated with this system. */
    readonly NetworkInterfaces?: OdataV4IdRef;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** The link to the operating system information associated with this system. */
    readonly OperatingSystem?: OdataV4IdRef;
    /** The link to a collection of PCIe devices that this computer system uses. */
    readonly PCIeDevices?: readonly OdataV4IdRef[];
    'PCIeDevices@odata.count'?: OdataV4Count;
    /** The link to a collection of PCIe functions that this computer system uses. */
    readonly PCIeFunctions?: readonly OdataV4IdRef[];
    'PCIeFunctions@odata.count'?: OdataV4Count;
    /**
     * The part number for this system.
     * @nullable
     */
    readonly PartNumber?: string | null;
    /**
     * The number of seconds to delay power on after a `Reset` action requesting `PowerCycle` or `FullPowerCycle`.  Zero seconds indicates no delay.
     * @nullable
     */
    PowerCycleDelaySeconds?: number | null;
    /**
     * The power mode setting of the computer system.
     * @nullable
     */
    PowerMode?: ComputerSystemPowerMode;
    /**
     * The number of seconds to delay power off during a reset.  Zero seconds indicates no delay to power off.
     * @nullable
     */
    PowerOffDelaySeconds?: number | null;
    /**
     * The number of seconds to delay power on after an externally performed power cycle or during a reset.  Zero seconds indicates no delay to power up.
     * @nullable
     */
    PowerOnDelaySeconds?: number | null;
    /** The desired power state of the system when power is restored after a power loss. */
    PowerRestorePolicy?: ComputerSystemPowerRestorePolicyTypes;
    /**
     * The current power state of the system.
     * @nullable
     */
    readonly PowerState?: ResourcePowerState;
    /** The central processors of the system in general detail. */
    ProcessorSummary?: ComputerSystemProcessorSummary;
    /** The link to the collection of processors associated with this system. */
    readonly Processors?: OdataV4IdRef;
    /** The link to a collection of redundancy entities.  Each entity specifies a kind and level of redundancy and a collection, or redundancy set, of other computer systems that provide the specified redundancy to this computer system. */
    readonly Redundancy?: readonly Redundancy[];
    'Redundancy@odata.count'?: OdataV4Count;
    /**
     * The manufacturer SKU for this system.
     * @nullable
     */
    readonly SKU?: string | null;
    /** The link to the UEFI Secure Boot associated with this system. */
    readonly SecureBoot?: OdataV4IdRef;
    /** The serial console services that this system provides. */
    SerialConsole?: ComputerSystemHostSerialConsole;
    /**
     * The serial number for this system.
     * @nullable
     */
    readonly SerialNumber?: string | null;
    /** The link to the collection of storage devices associated with this system. */
    readonly SimpleStorage?: OdataV4IdRef;
    /** The status and health of the resource and its subordinate or dependent resources. */
    Status?: ResourceStatus;
    /** The link to the collection of storage devices associated with this system. */
    readonly Storage?: OdataV4IdRef;
    /**
     * The sub-model for this system.
     * @nullable
     */
    readonly SubModel?: string | null;
    /** The type of computer system that this resource represents. */
    readonly SystemType?: ComputerSystemSystemType;
    /**
     * An array of trusted modules in the system.
     * @deprecated
     */
    TrustedModules?: ComputerSystemTrustedModules[];
    /** The link to a collection of USB controllers for this system. */
    readonly USBControllers?: OdataV4IdRef;
    /**
     * The UUID for this system.
     * @nullable
     */
    readonly UUID?: ResourceUUID;
    /** The link to the virtual media services for this system. */
    readonly VirtualMedia?: OdataV4IdRef;
    /** The information about the virtual media service of this system. */
    VirtualMediaConfig?: ComputerSystemVirtualMediaConfig;
}
