/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.27.0
 */
export type ComputerSystemSystemType =
    (typeof ComputerSystemSystemType)[keyof typeof ComputerSystemSystemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemSystemType = {
    /** A computer system. */
    Physical: 'Physical',
    /** A virtual machine instance running on this system. */
    Virtual: 'Virtual',
    /** An operating system instance. */
    OS: 'OS',
    /** A hardware-based partition of a computer system. */
    PhysicallyPartitioned: 'PhysicallyPartitioned',
    /** A virtual or software-based partition of a computer system. */
    VirtuallyPartitioned: 'VirtuallyPartitioned',
    /** A computer system constructed by binding resource blocks together. */
    Composed: 'Composed',
    /** A computer system that performs the functions of a data processing unit, such as a SmartNIC. */
    DPU: 'DPU',
} as const;
