/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.27.0
 */
export type ComputerSystemTrustedModuleRequiredToBoot =
    (typeof ComputerSystemTrustedModuleRequiredToBoot)[keyof typeof ComputerSystemTrustedModuleRequiredToBoot];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerSystemTrustedModuleRequiredToBoot = {
    /** No Trusted Module requirement to boot. */
    Disabled: 'Disabled',
    /** A functional Trusted Module is required to boot. */
    Required: 'Required',
} as const;
