/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ComputerSystemCompositionUseCase } from './ComputerSystemCompositionUseCase';

/**
 * Information about the composition capabilities and state of a computer system.
 * @version 1.27.0
 */
export interface ComputerSystemComposition {
    /** The composition use cases in which this computer system can participate. */
    readonly UseCases?: readonly ComputerSystemCompositionUseCase[];
}
