/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ComputerSystemGraphicalConnectTypesSupported } from './ComputerSystemGraphicalConnectTypesSupported';

/**
 * The information about a graphical console service for this system.
 * @version 1.27.0
 */
export interface ComputerSystemHostGraphicalConsole {
    /** This property enumerates the graphical console connection types that the implementation allows. */
    readonly ConnectTypesSupported?: readonly ComputerSystemGraphicalConnectTypesSupported[];
    /**
     * The maximum number of service sessions, regardless of protocol, that this system can support.
     * @minimum 0
     */
    readonly MaxConcurrentSessions?: number;
    /**
     * The protocol port.
     * @minimum 0
     * @nullable
     */
    Port?: number | null;
    /** An indication of whether the service is enabled for this system. */
    ServiceEnabled?: boolean;
}
