/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.7.0
 */
export type ControlMode = (typeof ControlMode)[keyof typeof ControlMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlMode = {
    /** Automatically adjust control to meet the set point. */
    Automatic: 'Automatic',
    /** User override of the automatic set point value. */
    Override: 'Override',
    /** No automatic adjustments are made to the control. */
    Manual: 'Manual',
    /** The control has been disabled. */
    Disabled: 'Disabled',
} as const;
