/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ControlMode } from './ControlMode';

/**
 * The `Control` schema describes a control point and its properties.
 * @version 1.7.0
 */
export interface ControlSingleExcerpt {
    /**
     * The maximum possible setting for this control.
     * @nullable
     */
    readonly AllowableMax?: number | null;
    /**
     * The minimum possible setting for this control.
     * @nullable
     */
    readonly AllowableMin?: number | null;
    /**
     * The current operating mode of the control.
     * @nullable
     */
    ControlMode?: ControlMode;
    /**
     * The link to the resource that provides the data for this control.
     * @nullable
     */
    readonly DataSourceUri?: string | null;
    /**
     * The default set point of the control.
     * @nullable
     */
    readonly DefaultSetPoint?: number | null;
    /**
     * The reading of the sensor associated with this control.
     * @nullable
     */
    readonly Reading?: number | null;
    /**
     * The desired set point of the control.
     * @nullable
     */
    SetPoint?: number | null;
}
