/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { EnvironmentMetricsResetMetrics } from './EnvironmentMetricsResetMetrics';
import type { EnvironmentMetricsResetToDefaults } from './EnvironmentMetricsResetToDefaults';
import type { EnvironmentMetricsOemActions } from './EnvironmentMetricsOemActions';

/**
 * The available actions for this resource.
 * @version 1.5.0
 */
export interface EnvironmentMetricsActions {
    '#EnvironmentMetrics.ResetMetrics'?: EnvironmentMetricsResetMetrics;
    '#EnvironmentMetrics.ResetToDefaults'?: EnvironmentMetricsResetToDefaults;
    /** The available OEM-specific actions for this resource. */
    Oem?: EnvironmentMetricsOemActions;
}
