/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @deprecated
 */
export type EventType = (typeof EventType)[keyof typeof EventType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventType = {
    /** The status of a resource has changed. */
    StatusChange: 'StatusChange',
    /** A resource has been updated. */
    ResourceUpdated: 'ResourceUpdated',
    /** A resource has been added. */
    ResourceAdded: 'ResourceAdded',
    /** A resource has been removed. */
    ResourceRemoved: 'ResourceRemoved',
    /** A condition requires attention. */
    Alert: 'Alert',
    /** The telemetry service is sending a metric report. */
    MetricReport: 'MetricReport',
    /** Because `EventType` is deprecated as of Redfish Specification v1.6, the event is based on a registry or resource but not an `EventType`. */
    Other: 'Other',
} as const;
