/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.21.0
 */
export type LogEntrySensorType =
    (typeof LogEntrySensorType)[keyof typeof LogEntrySensorType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogEntrySensorType = {
    /** A platform security sensor. */
    Platform_Security_Violation_Attempt: 'Platform Security Violation Attempt',
    /** A temperature sensor. */
    Temperature: 'Temperature',
    /** A voltage sensor. */
    Voltage: 'Voltage',
    /** A current sensor. */
    Current: 'Current',
    /** A fan sensor. */
    Fan: 'Fan',
    /** A physical security sensor. */
    Physical_Chassis_Security: 'Physical Chassis Security',
    /** A sensor for a processor. */
    Processor: 'Processor',
    /** A sensor for a power supply or DC-to-DC converter. */
    'Power_Supply_/_Converter': 'Power Supply / Converter',
    /** A sensor for a power unit. */
    PowerUnit: 'PowerUnit',
    /** A sensor for a cooling device. */
    CoolingDevice: 'CoolingDevice',
    /** A sensor for a miscellaneous analog sensor. */
    'Other_Units-based_Sensor': 'Other Units-based Sensor',
    /** A sensor for a memory device. */
    Memory: 'Memory',
    /** A sensor for a drive slot or bay. */
    'Drive_Slot/Bay': 'Drive Slot/Bay',
    /** A sensor for a POST memory resize event. */
    POST_Memory_Resize: 'POST Memory Resize',
    /** A sensor for a system firmware progress event. */
    System_Firmware_Progress: 'System Firmware Progress',
    /** A sensor for the event log. */
    Event_Logging_Disabled: 'Event Logging Disabled',
    /** A sensor for a system event. */
    System_Event: 'System Event',
    /** A sensor for a critical interrupt event. */
    Critical_Interrupt: 'Critical Interrupt',
    /** A sensor for a button or switch. */
    'Button/Switch': 'Button/Switch',
    /** A sensor for a module or board. */
    'Module/Board': 'Module/Board',
    /** A sensor for a microcontroller or coprocessor. */
    'Microcontroller/Coprocessor': 'Microcontroller/Coprocessor',
    /** A sensor for an add-in card. */
    'Add-in_Card': 'Add-in Card',
    /** A sensor for a chassis. */
    Chassis: 'Chassis',
    /** A sensor for a chipset. */
    ChipSet: 'ChipSet',
    /** A sensor for another type of FRU. */
    Other_FRU: 'Other FRU',
    /** A sensor for a cable or interconnect device type. */
    'Cable/Interconnect': 'Cable/Interconnect',
    /** A sensor for a terminator. */
    Terminator: 'Terminator',
    /** A sensor for a system boot or restart event. */
    'SystemBoot/Restart': 'SystemBoot/Restart',
    /** A sensor for a boot error event. */
    Boot_Error: 'Boot Error',
    /** A sensor for a base OS boot or installation status event. */
    'BaseOSBoot/InstallationStatus': 'BaseOSBoot/InstallationStatus',
    /** A sensor for an OS stop or shutdown event. */
    'OS_Stop/Shutdown': 'OS Stop/Shutdown',
    /** A sensor for a slot or connector. */
    'Slot/Connector': 'Slot/Connector',
    /** A sensor for an ACPI power state event. */
    System_ACPI_PowerState: 'System ACPI PowerState',
    /** A sensor for a watchdog event. */
    Watchdog: 'Watchdog',
    /** A sensor for a platform alert event. */
    Platform_Alert: 'Platform Alert',
    /** A sensor for an entity presence event. */
    Entity_Presence: 'Entity Presence',
    /** A sensor for a monitor ASIC or IC. */
    'Monitor_ASIC/IC': 'Monitor ASIC/IC',
    /** A sensor for a LAN device. */
    LAN: 'LAN',
    /** A sensor for a management subsystem health event. */
    Management_Subsystem_Health: 'Management Subsystem Health',
    /** A sensor for a battery. */
    Battery: 'Battery',
    /** A sensor for a session audit event. */
    Session_Audit: 'Session Audit',
    /** A sensor for a version change event. */
    Version_Change: 'Version Change',
    /** A sensor for a FRU state event. */
    FRUState: 'FRUState',
    /** An OEM-defined sensor. */
    OEM: 'OEM',
} as const;
