/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceOem } from './ResourceOem';

/**
 * Details for a CPER section or record associated with a log entry.
 * @version 1.21.0
 */
export interface LogEntryCPER {
    /**
     * The CPER Notification Type for a CPER record.
     * @nullable
     * @pattern ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
     */
    readonly NotificationType?: string | null;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * The CPER Section Type.
     * @nullable
     * @pattern ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
     */
    readonly SectionType?: string | null;
}
