/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.21.0
 */
export type LogEntryOriginatorTypes =
    (typeof LogEntryOriginatorTypes)[keyof typeof LogEntryOriginatorTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogEntryOriginatorTypes = {
    /** A client of the service created this log entry. */
    Client: 'Client',
    /** A process running on the service created this log entry. */
    Internal: 'Internal',
    /** A process not running on the service but running on a supporting service, such as RDE implementations, UEFI, or host processes, created this log entry. */
    SupportingService: 'SupportingService',
} as const;
