/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.21.0
 */
export type LogEntryType = (typeof LogEntryType)[keyof typeof LogEntryType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogEntryType = {
    /** A Redfish-defined message. */
    Event: 'Event',
    /** A legacy IPMI System Event Log (SEL) entry. */
    SEL: 'SEL',
    /** An entry in an OEM-defined format. */
    Oem: 'Oem',
    /** A CXL log entry. */
    CXL: 'CXL',
} as const;
