/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { LogEntryOemActions } from './LogEntryOemActions';

/**
 * The available actions for this resource.
 * @version 1.21.0
 */
export interface LogEntryActions {
    /** The available OEM-specific actions for this resource. */
    Oem?: LogEntryOemActions;
}
