/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.21.0
 */
export type LogEntryCode = (typeof LogEntryCode)[keyof typeof LogEntryCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogEntryCode = {
    /** The condition has been asserted. */
    Assert: 'Assert',
    /** The condition has been deasserted. */
    Deassert: 'Deassert',
    /** The reading crossed the Lower Non-critical threshold while going low. */
    'Lower_Non-critical_-_going_low': 'Lower Non-critical - going low',
    /** The reading crossed the Lower Non-critical threshold while going high. */
    'Lower_Non-critical_-_going_high': 'Lower Non-critical - going high',
    /** The reading crossed the Lower Critical threshold while going low. */
    'Lower_Critical_-_going_low': 'Lower Critical - going low',
    /** The reading crossed the Lower Critical threshold while going high. */
    'Lower_Critical_-_going_high': 'Lower Critical - going high',
    /** The reading crossed the Lower Non-recoverable threshold while going low. */
    'Lower_Non-recoverable_-_going_low': 'Lower Non-recoverable - going low',
    /** The reading crossed the Lower Non-recoverable threshold while going high. */
    'Lower_Non-recoverable_-_going_high': 'Lower Non-recoverable - going high',
    /** The reading crossed the Upper Non-critical threshold while going low. */
    'Upper_Non-critical_-_going_low': 'Upper Non-critical - going low',
    /** The reading crossed the Upper Non-critical threshold while going high. */
    'Upper_Non-critical_-_going_high': 'Upper Non-critical - going high',
    /** The reading crossed the Upper Critical threshold while going low. */
    'Upper_Critical_-_going_low': 'Upper Critical - going low',
    /** The reading crossed the Upper Critical threshold while going high. */
    'Upper_Critical_-_going_high': 'Upper Critical - going high',
    /** The reading crossed the Upper Non-recoverable threshold while going low. */
    'Upper_Non-recoverable_-_going_low': 'Upper Non-recoverable - going low',
    /** The reading crossed the Upper Non-recoverable threshold while going high. */
    'Upper_Non-recoverable_-_going_high': 'Upper Non-recoverable - going high',
    /** The state transitioned to idle. */
    Transition_to_Idle: 'Transition to Idle',
    /** The state transitioned to active. */
    Transition_to_Active: 'Transition to Active',
    /** The state transitioned to busy. */
    Transition_to_Busy: 'Transition to Busy',
    /** The state has been deasserted. */
    State_Deasserted: 'State Deasserted',
    /** The state has been asserted. */
    State_Asserted: 'State Asserted',
    /** A Predictive Failure is no longer present. */
    Predictive_Failure_deasserted: 'Predictive Failure deasserted',
    /** A Predictive Failure has been detected. */
    Predictive_Failure_asserted: 'Predictive Failure asserted',
    /** A limit has not been exceeded. */
    Limit_Not_Exceeded: 'Limit Not Exceeded',
    /** A limit has been exceeded. */
    Limit_Exceeded: 'Limit Exceeded',
    /** Performance meets expectations. */
    Performance_Met: 'Performance Met',
    /** Performance does not meet expectations. */
    Performance_Lags: 'Performance Lags',
    /** A state has changed to OK. */
    Transition_to_OK: 'Transition to OK',
    /** A state has changed to Non-Critical from OK. */
    'Transition_to_Non-Critical_from_OK': 'Transition to Non-Critical from OK',
    /** A state has changed to Critical from less severe. */
    Transition_to_Critical_from_less_severe:
        'Transition to Critical from less severe',
    /** A state has changed to Non-recoverable from less severe. */
    'Transition_to_Non-recoverable_from_less_severe':
        'Transition to Non-recoverable from less severe',
    /** A state has changed to Non-Critical from more severe. */
    'Transition_to_Non-Critical_from_more_severe':
        'Transition to Non-Critical from more severe',
    /** A state has changed to Critical from Non-recoverable. */
    'Transition_to_Critical_from_Non-recoverable':
        'Transition to Critical from Non-recoverable',
    /** A state has changed to Non-recoverable. */
    'Transition_to_Non-recoverable': 'Transition to Non-recoverable',
    /** A monitor event. */
    Monitor: 'Monitor',
    /** An informational event. */
    Informational: 'Informational',
    /** A device has been removed or is absent. */
    'Device_Removed_/_Device_Absent': 'Device Removed / Device Absent',
    /** A device has been inserted or is present. */
    'Device_Inserted_/_Device_Present': 'Device Inserted / Device Present',
    /** A device has been disabled. */
    Device_Disabled: 'Device Disabled',
    /** A device has been enabled. */
    Device_Enabled: 'Device Enabled',
    /** A state has transitioned to Running. */
    Transition_to_Running: 'Transition to Running',
    /** A state has transitioned to In Test. */
    Transition_to_In_Test: 'Transition to In Test',
    /** A state has transitioned to Power Off. */
    Transition_to_Power_Off: 'Transition to Power Off',
    /** A state has transitioned to On Line. */
    Transition_to_On_Line: 'Transition to On Line',
    /** A state has transitioned to Off Line. */
    Transition_to_Off_Line: 'Transition to Off Line',
    /** A state has transitioned to Off Duty. */
    Transition_to_Off_Duty: 'Transition to Off Duty',
    /** A state has transitioned to Degraded. */
    Transition_to_Degraded: 'Transition to Degraded',
    /** A state has transitioned to Power Save. */
    Transition_to_Power_Save: 'Transition to Power Save',
    /** An install error has been detected. */
    Install_Error: 'Install Error',
    /** Indicates that full redundancy has been regained. */
    Fully_Redundant: 'Fully Redundant',
    /** Entered any non-redundant state, including Non-redundant: Insufficient Resources. */
    Redundancy_Lost: 'Redundancy Lost',
    /** Redundancy still exists, but at less than full level. */
    Redundancy_Degraded: 'Redundancy Degraded',
    /** Redundancy has been lost but unit is functioning with minimum resources needed for normal operation. */
    'Non-redundant:Sufficient_Resources_from_Redundant':
        'Non-redundant:Sufficient Resources from Redundant',
    /** Unit has regained minimum resources needed for normal operation. */
    'Non-redundant:Sufficient_Resources_from_Insufficient_Resources':
        'Non-redundant:Sufficient Resources from Insufficient Resources',
    /** Unit is non-redundant and has insufficient resources to maintain normal operation. */
    'Non-redundant:Insufficient_Resources':
        'Non-redundant:Insufficient Resources',
    /** Unit has lost some redundant resource(s) but is still in a redundant state. */
    Redundancy_Degraded_from_Fully_Redundant:
        'Redundancy Degraded from Fully Redundant',
    /** Unit has regained some resource(s) and is redundant but not fully redundant. */
    'Redundancy_Degraded_from_Non-redundant':
        'Redundancy Degraded from Non-redundant',
    /** The ACPI-defined D0 power state. */
    D0_Power_State: 'D0 Power State',
    /** The ACPI-defined D1 power state. */
    D1_Power_State: 'D1 Power State',
    /** The ACPI-defined D2 power state. */
    D2_Power_State: 'D2 Power State',
    /** The ACPI-defined D3 power state. */
    D3_Power_State: 'D3 Power State',
    /** An OEM-defined event. */
    OEM: 'OEM',
} as const;
