/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.21.0
 */
export type LogEntryEventSeverity =
    (typeof LogEntryEventSeverity)[keyof typeof LogEntryEventSeverity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogEntryEventSeverity = {
    /** Informational or operating normally. */
    OK: 'OK',
    /** A condition that requires attention. */
    Warning: 'Warning',
    /** A critical condition that requires immediate attention. */
    Critical: 'Critical',
} as const;
