/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Context } from './OdataV4Context';
import type { OdataV4Etag } from './OdataV4Etag';
import type { OdataV4Id } from './OdataV4Id';
import type { OdataV4Type } from './OdataV4Type';
import type { LogEntryActions } from './LogEntryActions';
import type { LogEntryCPER } from './LogEntryCPER';
import type { LogEntryCXLEntryType } from './LogEntryCXLEntryType';
import type { ResourceDescription } from './ResourceDescription';
import type { LogEntryLogDiagnosticDataTypes } from './LogEntryLogDiagnosticDataTypes';
import type { LogEntryCode } from './LogEntryCode';
import type { LogEntryType } from './LogEntryType';
import type { EventType } from './EventType';
import type { ResourceId } from './ResourceId';
import type { LogEntryLinks } from './LogEntryLinks';
import type { ResourceName } from './ResourceName';
import type { ResourceOem } from './ResourceOem';
import type { LogEntryOriginatorTypes } from './LogEntryOriginatorTypes';
import type { ResolutionStep } from './ResolutionStep';
import type { LogEntrySensorType } from './LogEntrySensorType';
import type { LogEntryEventSeverity } from './LogEntryEventSeverity';

/**
 * The `LogEntry` schema defines the record format for a log.  It is designed for Redfish event logs, which utilize messages defined in a Message Registry and referenced by a `MessageId`.  For standard message definitions, see DSP2065.  Other log formats, including OEM-specific definitions and the IPMI System Event Log (SEL) are also supported.  The `EntryType` field indicates the type of log and the resource includes several additional properties dependent on the `EntryType`.
 * @version 1.21.0
 */
export interface LogEntry {
    '@odata.context'?: OdataV4Context;
    '@odata.etag'?: OdataV4Etag;
    '@odata.id': OdataV4Id;
    '@odata.type': OdataV4Type;
    /** The available actions for this resource. */
    Actions?: LogEntryActions;
    /**
     * The size of the additional data for this log entry.
     * @nullable
     */
    readonly AdditionalDataSizeBytes?: number | null;
    /**
     * The URI at which to access the additional data for this log entry, such as diagnostic data, image captures, or other files.
     * @nullable
     */
    readonly AdditionalDataURI?: string | null;
    /** Details for a CPER section or record associated with this log entry. */
    CPER?: LogEntryCPER;
    /** The specific CXL entry type. */
    readonly CXLEntryType?: LogEntryCXLEntryType;
    /** The date and time when the log entry was created. */
    readonly Created?: string;
    /** @nullable */
    readonly Description?: ResourceDescription;
    /**
     * A Base64-encoded set of diagnostic data associated with this log entry.
     * @nullable
     */
    readonly DiagnosticData?: string | null;
    /**
     * The type of data available in the `DiagnosticData` property or retrieved from the URI specified by the `AdditionalDataURI` property.
     * @nullable
     */
    readonly DiagnosticDataType?: LogEntryLogDiagnosticDataTypes;
    /**
     * The entry code for the log entry if the entry type is `SEL`.
     * @nullable
     */
    readonly EntryCode?: LogEntryCode;
    /** The type of log entry. */
    readonly EntryType: LogEntryType;
    /**
     * An identifier that correlates events with the same cause.
     * @nullable
     */
    readonly EventGroupId?: number | null;
    /** The unique instance identifier for an event. */
    readonly EventId?: string;
    /** The date and time when the event occurred. */
    readonly EventTimestamp?: string;
    /**
     * The type of event recorded in this log.
     * @deprecated
     */
    readonly EventType?: EventType;
    /** The timestamp of the first overflow captured after this log entry. */
    readonly FirstOverflowTimestamp?: string;
    /**
     * An identifier of the device that has generated the IPMI SEL Event Record.
     * @nullable
     * @pattern ^0[xX](([a-fA-F]|[0-9]){2}){2}$
     */
    readonly GeneratorId?: string | null;
    readonly Id: ResourceId;
    /** The timestamp of the last overflow captured after this log entry. */
    readonly LastOverflowTimestamp?: string;
    /** The links to other resources that are related to this resource. */
    Links?: LogEntryLinks;
    /**
     * The message of the log entry.  This property decodes from the entry type.  If the entry type is `Event`, this property contains a message.  If the entry type is `SEL`, this property contains an SEL-specific message.  If the entry type is `CXL`, this property contains a CXL event record.  Otherwise, this property contains an OEM-specific log entry.  In most cases, this property contains the actual log entry.
     * @nullable
     */
    readonly Message?: string | null;
    /** An array of message arguments that are substituted for the arguments in the message when looked up in the message registry. */
    readonly MessageArgs?: readonly string[];
    /** The `MessageId`, event data, or OEM-specific information.  This property decodes from the entry type.  If the entry type is `Event`, this property contains a Redfish Specification-defined `MessageId`.  If the entry type is `SEL`, this property contains the Event Data.  Otherwise, this property contains OEM-specific information. */
    readonly MessageId?: string;
    /** The date and time when the log entry was last modified. */
    readonly Modified?: string;
    readonly Name: ResourceName;
    /**
     * The OEM-defined type of data available in the `DiagnosticData` property or retrieved from the URI specified by the `AdditionalDataURI` property.
     * @nullable
     */
    readonly OEMDiagnosticDataType?: string | null;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * The OEM-specific entry code, if the `LogEntryCode` type is `OEM`.
     * @nullable
     */
    readonly OemLogEntryCode?: string | null;
    /**
     * The OEM-specific format of the entry.  If the entry type is `Oem`, this property contains more information about the record format from the OEM.
     * @nullable
     */
    readonly OemRecordFormat?: string | null;
    /**
     * The OEM-specific sensor type if the sensor type is `OEM`.
     * @nullable
     */
    readonly OemSensorType?: string | null;
    /**
     * The IP address, with scheme, of the user associated with the log entry.
     * @nullable
     * @pattern ^.+:\/\/.+$
     */
    readonly OriginAddress?: string | null;
    /**
     * Indicates whether the `OriginOfCondition` link is unavailable, such as after the deletion of the resource.
     * @nullable
     */
    readonly OriginOfConditionUnavailable?: boolean | null;
    /** The source of the log entry. */
    readonly Originator?: string;
    /** The type of originator data. */
    readonly OriginatorType?: LogEntryOriginatorTypes;
    /** The count of overflow errors that occurred after this log entry. */
    readonly OverflowErrorCount?: number;
    /**
     * The part number associated with the source of this log entry.
     * @nullable
     */
    readonly PartNumber?: string | null;
    /** Indicates whether the log entry is persistent across a cold reset of the device. */
    readonly Persistency?: boolean;
    /** Used to provide suggestions on how to resolve the situation that caused the log entry. */
    readonly Resolution?: string;
    /** The list of recommended steps to resolve the cause of the log entry. */
    ResolutionSteps?: ResolutionStep[];
    /**
     * Indicates if the cause of the log entry has been resolved or repaired.
     * @nullable
     */
    Resolved?: boolean | null;
    /**
     * The IPMI-defined sensor number.
     * @nullable
     */
    readonly SensorNumber?: number | null;
    /**
     * The sensor type to which the log entry pertains if the entry type is `SEL`.
     * @nullable
     */
    readonly SensorType?: LogEntrySensorType;
    /**
     * The serial number associated with the source of this log entry.
     * @nullable
     */
    readonly SerialNumber?: string | null;
    /**
     * Indicates if the log entry has been sent to the service provider.
     * @nullable
     */
    readonly ServiceProviderNotified?: boolean | null;
    /**
     * The severity of the log entry.
     * @nullable
     */
    readonly Severity?: LogEntryEventSeverity;
    /** Indicates this log entry is equivalent to a more specific log entry within the same `EventGroupId`. */
    readonly SpecificEventExistsInGroup?: boolean;
    /**
     * The source of authentication for the username property associated with the log entry.
     * @nullable
     */
    readonly UserAuthenticationSource?: string | null;
    /**
     * The username of the account associated with the log entry.
     * @nullable
     */
    readonly Username?: string | null;
}
