/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.21.0
 */
export type LogEntryCXLEntryType =
    (typeof LogEntryCXLEntryType)[keyof typeof LogEntryCXLEntryType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogEntryCXLEntryType = {
    /** A CXL Dynamic Capacity log entry. */
    DynamicCapacity: 'DynamicCapacity',
    /** A CXL informational log entry. */
    Informational: 'Informational',
    /** A CXL warning log entry. */
    Warning: 'Warning',
    /** A CXL failure log entry. */
    Failure: 'Failure',
    /** A CXL fatal log entry. */
    Fatal: 'Fatal',
} as const;
