/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.21.0
 */
export type LogEntryLogDiagnosticDataTypes =
    (typeof LogEntryLogDiagnosticDataTypes)[keyof typeof LogEntryLogDiagnosticDataTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogEntryLogDiagnosticDataTypes = {
    /** Manager diagnostic data. */
    Manager: 'Manager',
    /** Pre-OS diagnostic data. */
    PreOS: 'PreOS',
    /** Operating system (OS) diagnostic data. */
    OS: 'OS',
    /** OEM diagnostic data. */
    OEM: 'OEM',
    /** UEFI Common Platform Error Record. */
    CPER: 'CPER',
    /** A Section of a UEFI Common Platform Error Record. */
    CPERSection: 'CPERSection',
    /** Device diagnostic data. */
    Device: 'Device',
} as const;
