/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceOem } from './ResourceOem';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { OdataV4Count } from './OdataV4Count';

/**
 * The links to other resources that are related to this resource.
 * @version 1.21.0
 */
export interface LogEntryLinks {
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** The link to the resource that caused the log entry. */
    readonly OriginOfCondition?: OdataV4IdRef;
    /** An array of links to resources associated with this log entry. */
    readonly RelatedItem?: readonly OdataV4IdRef[];
    'RelatedItem@odata.count'?: OdataV4Count;
    /** An array of links to other log entries that are related to this log entry. */
    readonly RelatedLogEntries?: readonly OdataV4IdRef[];
    'RelatedLogEntries@odata.count'?: OdataV4Count;
}
