/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.24.0
 */
export type ManagerSecurityModeTypes =
    (typeof ManagerSecurityModeTypes)[keyof typeof ManagerSecurityModeTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManagerSecurityModeTypes = {
    /** This security mode indicates the implementation complies with FIPS 140-2. */
    FIPS_140_2: 'FIPS_140_2',
    /** This security mode indicates the implementation complies with FIPS 140-3. */
    FIPS_140_3: 'FIPS_140_3',
    /** This security mode indicates the implementation meets NSA Commercial National Security Algorithm Suite 1.0 requirements.  This mode requires FIPS 140-2 compliance. */
    CNSA_1_0: 'CNSA_1_0',
    /** This security mode indicates the implementation meets NSA Commercial National Security Algorithm Suite 2.0 requirements.  This mode requires FIPS 140-3 compliance. */
    CNSA_2_0: 'CNSA_2_0',
    /** This security mode indicates the implementation meets NSA Suite B cryptographic standards for Top Secret installations.  This mode requires FIPS 140-2 compliance. */
    SuiteB: 'SuiteB',
    /** This security mode indicates the implementation is in an OEM-specific security state. */
    OEM: 'OEM',
    /** This security mode indicates the implementation is in a vendor-specific default security state that does not match any other value. */
    Default: 'Default',
} as const;
