/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceOem } from './ResourceOem';
import type { OdataV4IdRef } from './OdataV4IdRef';

/**
 * The links to other resources that are related to this resource.
 * @version 1.14.1
 */
export interface ManagerAccountLinks {
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** The link to the Redfish role that defines the privileges for this account. */
    readonly Role?: OdataV4IdRef;
}
