/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.24.0
 */
export type ManagerCommandConnectTypesSupported =
    (typeof ManagerCommandConnectTypesSupported)[keyof typeof ManagerCommandConnectTypesSupported];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManagerCommandConnectTypesSupported = {
    /** The controller supports a command shell connection through the SSH protocol. */
    SSH: 'SSH',
    /** The controller supports a command shell connection through the Telnet protocol. */
    Telnet: 'Telnet',
    /** The controller supports a command shell connection through the IPMI Serial Over LAN (SOL) protocol. */
    IPMI: 'IPMI',
    /** The controller supports a command shell connection through an OEM-specific protocol. */
    Oem: 'Oem',
} as const;
