/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * This action randomly generates a new secret key for Time-based One-Time Password (TOTP) multi-factor authentication for this account.
 * @version 1.14.1
 */
export interface ManagerAccountGenerateSecretKey {
    /** Link to invoke action */
    target?: string;
    /** Friendly action name */
    title?: string;
}
