/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Context } from './OdataV4Context';
import type { OdataV4Etag } from './OdataV4Etag';
import type { OdataV4Id } from './OdataV4Id';
import type { OdataV4Type } from './OdataV4Type';
import type { ManagerAccountAccountTypes } from './ManagerAccountAccountTypes';
import type { ManagerAccountActions } from './ManagerAccountActions';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { ResourceDescription } from './ResourceDescription';
import type { ResourceId } from './ResourceId';
import type { ManagerAccountLinks } from './ManagerAccountLinks';
import type { AccountServiceMFABypass } from './AccountServiceMFABypass';
import type { ResourceName } from './ResourceName';
import type { ResourceOem } from './ResourceOem';
import type { ManagerAccountSNMPUserInfo } from './ManagerAccountSNMPUserInfo';

/**
 * The `ManagerAccount` schema defines the user accounts that are owned by a manager.  Changes to a manager account might affect the current Redfish service connection if this manager is responsible for the Redfish service.
 * @version 1.14.1
 */
export interface ManagerAccount {
    '@odata.context'?: OdataV4Context;
    '@odata.etag'?: OdataV4Etag;
    '@odata.id': OdataV4Id;
    '@odata.type': OdataV4Type;
    /**
     * Indicates the date and time when this account expires.  If `null`, the account never expires.
     * @nullable
     */
    AccountExpiration?: string | null;
    /** The list of services in the manager that the account is allowed to access. */
    AccountTypes: ManagerAccountAccountTypes[];
    /** The available actions for this resource. */
    Actions?: ManagerAccountActions;
    /** The link to a collection of user identity certificates for this account. */
    readonly Certificates?: OdataV4IdRef;
    /** @nullable */
    readonly Description?: ResourceDescription;
    /**
     * The email address associated with this account.
     * @nullable
     */
    EmailAddress?: string | null;
    /** An indication of whether an account is enabled.  An administrator can disable it without deleting the user information.  If `true`, the account is enabled and the user can log in.  If `false`, the account is disabled and, in the future, the user cannot log in. */
    Enabled?: boolean;
    /** An indication of whether this account is a bootstrap account for the host interface. */
    readonly HostBootstrapAccount?: boolean;
    readonly Id: ResourceId;
    /** The link to the collection of keys that can be used to authenticate this account.  For example, an SSH public key could be added to this collection to allow for SSH public key authentication. */
    readonly Keys?: OdataV4IdRef;
    /** The links to other resources that are related to this resource. */
    Links?: ManagerAccountLinks;
    /** An indication of whether the account service automatically locked the account because the lockout threshold was exceeded.  To manually unlock the account before the lockout duration period, an administrator can change the property to `false` to clear the lockout condition. */
    Locked?: boolean;
    /**
     * The multi-factor authentication bypass settings for this account.
     * @nullable
     */
    MFABypass?: AccountServiceMFABypass;
    readonly Name: ResourceName;
    /** The OEM account types. */
    OEMAccountTypes?: (string | null)[];
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * The address used to receive one-time passcode messages for multi-factor authentication.
     * @nullable
     */
    OneTimePasscodeDeliveryAddress?: string | null;
    /**
     * The password.  Use this property with a `PATCH` or `PUT` to write the password for the account.  This property is `null` in responses.
     * @nullable
     */
    Password?: string | null;
    /**
     * An indication of whether the service requires that the password for this account be changed before further access to the account is allowed.
     * @nullable
     */
    PasswordChangeRequired?: boolean | null;
    /**
     * Indicates the date and time when this account password expires.  If `null`, the account password never expires.
     * @nullable
     */
    PasswordExpiration?: string | null;
    /**
     * The contact phone number associated with this account.
     * @nullable
     */
    PhoneNumber?: string | null;
    /** The role for this account. */
    RoleId?: string;
    /**
     * The SNMP settings for this account.
     * @nullable
     */
    SNMP?: ManagerAccountSNMPUserInfo;
    /** Indicates if the secret key for Time-based One-Time Password (TOTP) multi-factor authentication is set. */
    readonly SecretKeySet?: boolean;
    /**
     * Indicates if the service needs to use the account types exactly as specified when the account is created or updated.
     * @nullable
     */
    StrictAccountTypes?: boolean | null;
    /** The username for the account. */
    UserName?: string;
}
