/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ManagerCommandConnectTypesSupported } from './ManagerCommandConnectTypesSupported';

/**
 * The information about a command shell service that this manager provides.
 * @version 1.24.0
 */
export interface ManagerCommandShell {
    /** This property enumerates the command shell connection types that the implementation allows. */
    readonly ConnectTypesSupported?: readonly ManagerCommandConnectTypesSupported[];
    /**
     * The maximum number of service sessions, regardless of protocol, that this manager can support.
     * @minimum 0
     */
    readonly MaxConcurrentSessions?: number;
    /** An indication of whether the service is enabled for this manager. */
    ServiceEnabled?: boolean;
}
