/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Context } from './OdataV4Context';
import type { OdataV4Etag } from './OdataV4Etag';
import type { OdataV4Id } from './OdataV4Id';
import type { OdataV4Type } from './OdataV4Type';
import type { ManagerActions } from './ManagerActions';
import type { SoftwareInventoryAdditionalVersions } from './SoftwareInventoryAdditionalVersions';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { ManagerCommandShell } from './ManagerCommandShell';
import type { ManagerDateTimeSource } from './ManagerDateTimeSource';
import type { ManagerDaylightSavingTime } from './ManagerDaylightSavingTime';
import type { ResourceDescription } from './ResourceDescription';
import type { ManagerGraphicalConsole } from './ManagerGraphicalConsole';
import type { ResourceId } from './ResourceId';
import type { ManagerLinks } from './ManagerLinks';
import type { ResourceLocation } from './ResourceLocation';
import type { ManagerType } from './ManagerType';
import type { SoftwareInventoryMeasurementBlock } from './SoftwareInventoryMeasurementBlock';
import type { ResourceName } from './ResourceName';
import type { ResourceOem } from './ResourceOem';
import type { ResourcePowerState } from './ResourcePowerState';
import type { Redundancy } from './Redundancy';
import type { OdataV4Count } from './OdataV4Count';
import type { ManagerSecurityModeTypes } from './ManagerSecurityModeTypes';
import type { ManagerSerialConsole } from './ManagerSerialConsole';
import type { ResourceUUID } from './ResourceUUID';
import type { ResourceStatus } from './ResourceStatus';

/**
 * In Redfish, a manager is a systems management entity that can implement or provide access to a Redfish service.  Examples of managers are BMCs (baseboard management controllers), enclosure managers, management controllers, and other subsystems that are assigned manageability functions.  An implementation can have multiple managers, which might be directly accessible through a Redfish-defined interface.
 * @version 1.24.0
 */
export interface Manager {
    '@odata.context'?: OdataV4Context;
    '@odata.etag'?: OdataV4Etag;
    '@odata.id': OdataV4Id;
    '@odata.type': OdataV4Type;
    /** The available actions for this resource. */
    Actions?: ManagerActions;
    /** The additional firmware versions of the manager. */
    AdditionalFirmwareVersions?: SoftwareInventoryAdditionalVersions;
    /** An indication of whether the manager is configured for automatic Daylight Saving Time (DST) adjustment. */
    AutoDSTEnabled?: boolean;
    /** The link to a collection of certificates for device identity and attestation. */
    readonly Certificates?: OdataV4IdRef;
    /** The manager's command line user interface or command shell service. */
    CommandShell?: ManagerCommandShell;
    /**
     * The current date and time with UTC offset of the manager.
     * @nullable
     */
    DateTime?: string | null;
    /**
     * The time offset from UTC that the `DateTime` property is in `+HH:MM` format.
     * @nullable
     * @pattern ^([-+][0-1][0-9]:[0-5][0-9])$
     */
    DateTimeLocalOffset?: string | null;
    /**
     * The source of the date and time of this manager, such as NTP, RTC, or firmware.
     * @nullable
     */
    DateTimeSource?: ManagerDateTimeSource;
    /** The daylight saving time settings for this manager. */
    DaylightSavingTime?: ManagerDaylightSavingTime;
    /** The dedicated network ports of the manager. */
    DedicatedNetworkPorts?: OdataV4IdRef;
    /** @nullable */
    readonly Description?: ResourceDescription;
    /** The link to a collection of NICs that this manager uses for network communication. */
    readonly EthernetInterfaces?: OdataV4IdRef;
    /**
     * The firmware version of this manager.
     * @nullable
     */
    readonly FirmwareVersion?: string | null;
    /** The manager's graphical console service. */
    GraphicalConsole?: ManagerGraphicalConsole;
    /** The link to a collection of host interfaces that this manager uses for local host communication.  Clients can find host interface configuration options and settings in this navigation property. */
    readonly HostInterfaces?: OdataV4IdRef;
    readonly Id: ResourceId;
    /** The date and time when the manager was last reset or rebooted. */
    readonly LastResetTime?: string;
    /** The links to other resources that are related to this resource. */
    Links?: ManagerLinks;
    /** The location of the manager. */
    Location?: ResourceLocation;
    /**
     * An indicator allowing an operator to physically locate this resource.
     * @nullable
     */
    LocationIndicatorActive?: boolean | null;
    /** The link to a collection of logs that the manager uses. */
    readonly LogServices?: OdataV4IdRef;
    /**
     * The diagnostic data for this manager.
     * @nullable
     */
    readonly ManagerDiagnosticData?: OdataV4IdRef;
    /** The type of manager that this resource represents. */
    readonly ManagerType?: ManagerType;
    /**
     * The manufacturer of this manager.
     * @nullable
     */
    readonly Manufacturer?: string | null;
    /**
     * An array of DSP0274-defined measurement blocks.
     * @deprecated
     */
    Measurements?: SoftwareInventoryMeasurementBlock[];
    /**
     * The model information of this manager, as defined by the manufacturer.
     * @nullable
     */
    readonly Model?: string | null;
    readonly Name: ResourceName;
    /** The link to the network services and their settings that the manager controls. */
    readonly NetworkProtocol?: OdataV4IdRef;
    /**
     * The OEM-specific security compliance mode(s) that the manager is currently configured to enforce.
     * @nullable
     */
    readonly OEMSecurityMode?: string | null;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * The part number of the manager.
     * @nullable
     */
    readonly PartNumber?: string | null;
    /**
     * The current power state of the manager.
     * @nullable
     */
    readonly PowerState?: ResourcePowerState;
    /**
     * An indication of whether the manager is prepared by the system for removal.
     * @nullable
     */
    ReadyToRemove?: boolean | null;
    /** The redundancy information for the managers of this system. */
    Redundancy?: Redundancy[];
    'Redundancy@odata.count'?: OdataV4Count;
    /** The link to the account service resource for the remote manager that this resource represents. */
    readonly RemoteAccountService?: OdataV4IdRef;
    /**
     * The URI of the Redfish service root for the remote manager that this resource represents.
     * @nullable
     */
    readonly RemoteRedfishServiceUri?: string | null;
    /** The security compliance mode that the manager is currently configured to enforce. */
    readonly SecurityMode?: ManagerSecurityModeTypes;
    /**
     * The security policy settings for this manager.
     * @nullable
     */
    readonly SecurityPolicy?: OdataV4IdRef;
    /**
     * The serial console service that this manager provides.
     * @deprecated
     */
    SerialConsole?: ManagerSerialConsole;
    /** The link to a collection of serial interfaces that this manager uses for serial and console communication. */
    readonly SerialInterfaces?: OdataV4IdRef;
    /**
     * The serial number of the manager.
     * @nullable
     */
    readonly SerialNumber?: string | null;
    /**
     * The UUID of the Redfish service that is hosted by this manager.
     * @nullable
     */
    readonly ServiceEntryPointUUID?: ResourceUUID;
    /**
     * A product instance identifier displayed in the Redfish service root.
     * @nullable
     */
    ServiceIdentification?: string | null;
    /**
     * The usage notification message displayed in the Redfish service root.
     * @nullable
     */
    ServiceUseNotification?: string | null;
    /** The shared network ports of the manager. */
    SharedNetworkPorts?: OdataV4IdRef;
    /**
     * The spare part number of the manager.
     * @nullable
     */
    readonly SparePartNumber?: string | null;
    /** The status and health of the resource and its subordinate or dependent resources. */
    Status?: ResourceStatus;
    /** The time zone of the manager. */
    TimeZoneName?: string;
    /** The USB ports of the manager. */
    USBPorts?: OdataV4IdRef;
    /**
     * The UUID for this manager.
     * @nullable
     */
    readonly UUID?: ResourceUUID;
    /**
     * The hardware version of this manager.
     * @nullable
     */
    readonly Version?: string | null;
    /**
     * The link to the virtual media services for this particular manager.
     * @deprecated
     */
    readonly VirtualMedia?: OdataV4IdRef;
}
