/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The `ForceFailover` action forces a failover of this manager to the manager used in the parameter.
 * @version 1.24.0
 */
export interface ManagerForceFailover {
    /** Link to invoke action */
    target?: string;
    /** Friendly action name */
    title?: string;
}
