/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The update security mode action updates the security mode for the manager.  This can cause the manager to reset and reset other settings to factory defaults.  Services might require the `ResetToDefaults` action to clear the security mode.
 * @version 1.24.0
 */
export interface ManagerUpdateSecurityMode {
    /** Link to invoke action */
    target?: string;
    /** Friendly action name */
    title?: string;
}
