/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.24.0
 */
export type ManagerDateTimeSource =
    (typeof ManagerDateTimeSource)[keyof typeof ManagerDateTimeSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManagerDateTimeSource = {
    /** The date and time is retrieved from the manager\'s real time clock (RTC). */
    RTC: 'RTC',
    /** The date and time is set and held by firmware. */
    Firmware: 'Firmware',
    /** The date and time is retrieved from the host. */
    Host: 'Host',
    /** The date and time source is a Network Time Protocol (NTP) server. */
    NTP: 'NTP',
    /** The date and time source is a Precision Time Protocol (PTP) server. */
    PTP: 'PTP',
} as const;
