/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.14.1
 */
export type ManagerAccountSNMPAuthenticationProtocols =
    (typeof ManagerAccountSNMPAuthenticationProtocols)[keyof typeof ManagerAccountSNMPAuthenticationProtocols];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManagerAccountSNMPAuthenticationProtocols = {
    /** No authentication. */
    None: 'None',
    /** HMAC-MD5-96 authentication. */
    HMAC_MD5: 'HMAC_MD5',
    /** HMAC-SHA-96 authentication. */
    HMAC_SHA96: 'HMAC_SHA96',
    /** HMAC-128-SHA-224 authentication. */
    HMAC128_SHA224: 'HMAC128_SHA224',
    /** HMAC-192-SHA-256 authentication. */
    HMAC192_SHA256: 'HMAC192_SHA256',
    /** HMAC-256-SHA-384 authentication. */
    HMAC256_SHA384: 'HMAC256_SHA384',
    /** HMAC-384-SHA-512 authentication. */
    HMAC384_SHA512: 'HMAC384_SHA512',
} as const;
