/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.24.0
 */
export type ManagerGraphicalConnectTypesSupported =
    (typeof ManagerGraphicalConnectTypesSupported)[keyof typeof ManagerGraphicalConnectTypesSupported];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManagerGraphicalConnectTypesSupported = {
    /** The controller supports a graphical console connection through a KVM-IP (redirection of Keyboard, Video, Mouse over IP) protocol. */
    KVMIP: 'KVMIP',
    /** The controller supports a graphical console connection through an OEM-specific protocol. */
    Oem: 'Oem',
} as const;
