/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ManagerAccountChangePassword } from './ManagerAccountChangePassword';
import type { ManagerAccountClearSecretKey } from './ManagerAccountClearSecretKey';
import type { ManagerAccountGenerateSecretKey } from './ManagerAccountGenerateSecretKey';
import type { ManagerAccountVerifyTimeBasedOneTimePassword } from './ManagerAccountVerifyTimeBasedOneTimePassword';
import type { ManagerAccountOemActions } from './ManagerAccountOemActions';

/**
 * The available actions for this resource.
 * @version 1.14.1
 */
export interface ManagerAccountActions {
    '#ManagerAccount.ChangePassword'?: ManagerAccountChangePassword;
    '#ManagerAccount.ClearSecretKey'?: ManagerAccountClearSecretKey;
    '#ManagerAccount.GenerateSecretKey'?: ManagerAccountGenerateSecretKey;
    '#ManagerAccount.VerifyTimeBasedOneTimePassword'?: ManagerAccountVerifyTimeBasedOneTimePassword;
    /** The available OEM-specific actions for this resource. */
    Oem?: ManagerAccountOemActions;
}
