/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The daylight saving time settings for a manager.
 * @version 1.24.0
 */
export interface ManagerDaylightSavingTime {
    /** The end date and time with UTC offset of daylight saving time. */
    EndDateTime?: string;
    /** The daylight saving time offset in minutes. */
    OffsetMinutes?: number;
    /** The start date and time with UTC offset of daylight saving time. */
    StartDateTime?: string;
    /** The time zone of the manager when daylight saving time is in effect. */
    TimeZoneName?: string;
}
