/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.14.1
 */
export type ManagerAccountSNMPEncryptionProtocols =
    (typeof ManagerAccountSNMPEncryptionProtocols)[keyof typeof ManagerAccountSNMPEncryptionProtocols];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManagerAccountSNMPEncryptionProtocols = {
    /** No encryption. */
    None: 'None',
    /** CBC-DES encryption. */
    CBC_DES: 'CBC_DES',
    /** CFB128-AES-128 encryption. */
    CFB128_AES128: 'CFB128_AES128',
    /** CFB128-AES-192 encryption. */
    CFB128_AES192: 'CFB128_AES192',
    /** CFB128-AES-256 encryption. */
    CFB128_AES256: 'CFB128_AES256',
} as const;
