/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The `ModifyRedundancySet` operation adds members to or removes members from a redundant group of managers.
 * @version 1.24.0
 */
export interface ManagerModifyRedundancySet {
    /** Link to invoke action */
    target?: string;
    /** Friendly action name */
    title?: string;
}
