/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ManagerForceFailover } from './ManagerForceFailover';
import type { ManagerModifyRedundancySet } from './ManagerModifyRedundancySet';
import type { ManagerReset } from './ManagerReset';
import type { ManagerResetToDefaults } from './ManagerResetToDefaults';
import type { ManagerUpdateSecurityMode } from './ManagerUpdateSecurityMode';
import type { ManagerOemActions } from './ManagerOemActions';

/**
 * The available actions for this resource.
 * @version 1.24.0
 */
export interface ManagerActions {
    '#Manager.ForceFailover'?: ManagerForceFailover;
    '#Manager.ModifyRedundancySet'?: ManagerModifyRedundancySet;
    '#Manager.Reset'?: ManagerReset;
    '#Manager.ResetToDefaults'?: ManagerResetToDefaults;
    '#Manager.UpdateSecurityMode'?: ManagerUpdateSecurityMode;
    /** The available OEM-specific actions for this resource. */
    Oem?: ManagerOemActions;
}
