/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * This action verifies a user-provided Time-based One-Time Password (TOTP).  This is to ensure the client's copy of the secret key is aligned with the secret key stored by the service.
 * @version 1.14.1
 */
export interface ManagerAccountVerifyTimeBasedOneTimePassword {
    /** Link to invoke action */
    target?: string;
    /** Friendly action name */
    title?: string;
}
