/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ManagerAccountSNMPAuthenticationProtocols } from './ManagerAccountSNMPAuthenticationProtocols';
import type { ManagerAccountSNMPEncryptionProtocols } from './ManagerAccountSNMPEncryptionProtocols';

/**
 * The SNMP settings for an account.
 * @version 1.14.1
 */
export interface ManagerAccountSNMPUserInfo {
    /**
     * The secret authentication key for SNMPv3.
     * @nullable
     * @pattern (^[ -~]+$)|(^Passphrase:[ -~]+$)|(^Hex:[0-9A-Fa-f]{24,96})|(^\*+$)
     */
    AuthenticationKey?: string | null;
    /** Indicates if the `AuthenticationKey` property is set. */
    readonly AuthenticationKeySet?: boolean;
    /**
     * The authentication protocol for SNMPv3.
     * @nullable
     */
    AuthenticationProtocol?: ManagerAccountSNMPAuthenticationProtocols;
    /**
     * The secret encryption key used in SNMPv3.
     * @nullable
     * @pattern (^[ -~]+$)|(^Passphrase:[ -~]+$)|(^Hex:[0-9A-Fa-f]{16,64}$)|(^\*+$)
     */
    EncryptionKey?: string | null;
    /** Indicates if the `EncryptionKey` property is set. */
    readonly EncryptionKeySet?: boolean;
    /**
     * The encryption protocol for SNMPv3.
     * @nullable
     */
    EncryptionProtocol?: ManagerAccountSNMPEncryptionProtocols;
}
