/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { OdataV4Count } from './OdataV4Count';
import type { ResourceOem } from './ResourceOem';

/**
 * The links to other resources that are related to this resource.
 * @version 1.24.0
 */
export interface ManagerLinks {
    /** The link to the software inventory resource that represents the active firmware image for this manager. */
    ActiveSoftwareImage?: OdataV4IdRef;
    /** The array of links to the managers responsible for managing this manager. */
    readonly ManagedBy?: readonly OdataV4IdRef[];
    'ManagedBy@odata.count'?: OdataV4Count;
    /** An array of links to the chassis this manager controls. */
    readonly ManagerForChassis?: readonly OdataV4IdRef[];
    'ManagerForChassis@odata.count'?: OdataV4Count;
    /** An array of links to the fabrics that this manager controls. */
    readonly ManagerForFabrics?: readonly OdataV4IdRef[];
    'ManagerForFabrics@odata.count'?: OdataV4Count;
    /** An array of links to the managers that are managed by this manager. */
    readonly ManagerForManagers?: readonly OdataV4IdRef[];
    'ManagerForManagers@odata.count'?: OdataV4Count;
    /** An array of links to the systems that this manager controls. */
    readonly ManagerForServers?: readonly OdataV4IdRef[];
    'ManagerForServers@odata.count'?: OdataV4Count;
    /** An array of links to the switches that this manager controls. */
    readonly ManagerForSwitches?: readonly OdataV4IdRef[];
    'ManagerForSwitches@odata.count'?: OdataV4Count;
    /** The link to the chassis where this manager is located. */
    readonly ManagerInChassis?: OdataV4IdRef;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * The network port currently used by this manager.  This allows selection of shared or dedicated ports for managers that support one or the other.  For managers that always have their dedicated port enabled, this allows the selection of which shared port to use.
     * @nullable
     */
    SelectedNetworkPort?: OdataV4IdRef;
    /** The images that are associated with this manager. */
    readonly SoftwareImages?: readonly OdataV4IdRef[];
    'SoftwareImages@odata.count'?: OdataV4Count;
}
