/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The reset action resets/reboots the manager.
 * @version 1.24.0
 */
export interface ManagerReset {
    /** Link to invoke action */
    target?: string;
    /** Friendly action name */
    title?: string;
}
