/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.24.0
 */
export type ManagerType = (typeof ManagerType)[keyof typeof ManagerType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManagerType = {
    /** A controller that primarily monitors or manages the operation of a device or system. */
    ManagementController: 'ManagementController',
    /** A controller that provides management functions for a chassis, group of devices, or group of systems with their own BMCs (baseboard management controllers).  An example of this is a manager that aggregates and orchestrates management functions across multiple BMCs in an enclosure. */
    EnclosureManager: 'EnclosureManager',
    /** A controller that provides management functions for one or more computer systems.  Commonly known as a BMC (baseboard management controller).  Examples of this include a BMC dedicated to one system or a multi-host manager providing BMC capabilities to multiple systems. */
    BMC: 'BMC',
    /** A controller that provides management functions for a whole or part of a rack.  An example of this is a manager that aggregates and orchestrates management functions across multiple managers, such as enclosure managers and BMCs (baseboard management controllers), in a rack. */
    RackManager: 'RackManager',
    /** A controller that provides management functions for a particular subsystem or group of devices as part of a larger system. */
    AuxiliaryController: 'AuxiliaryController',
    /** A software-based service that provides management functions. */
    Service: 'Service',
    /** A controller that primarily monitors or manages the operation of a group of fabric attached nodes and switches. */
    FabricManager: 'FabricManager',
} as const;
