/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceHealth } from './ResourceHealth';
import type { ResourceOem } from './ResourceOem';
import type { ResolutionStep } from './ResolutionStep';

/**
 * The message that the Redfish service returns.
 * @version 1.3.0
 */
export interface Message {
    /** The human-readable message. */
    readonly Message?: string;
    /** An array of message arguments that are substituted for the arguments in the message when looked up in the message registry. */
    readonly MessageArgs?: readonly string[];
    /** The identifier for the message. */
    readonly MessageId: string;
    /** The severity of the message. */
    readonly MessageSeverity?: ResourceHealth;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** A set of properties described by the message. */
    readonly RelatedProperties?: readonly string[];
    /** Used to provide suggestions on how to resolve the situation that caused the message. */
    readonly Resolution?: string;
    /** The list of recommended steps to resolve the situation that caused the message. */
    ResolutionSteps?: ResolutionStep[];
    /**
     * The severity of the message.
     * @deprecated
     */
    readonly Severity?: string;
    /**
     * The source of authentication for the username property associated with the message.
     * @nullable
     */
    readonly UserAuthenticationSource?: string | null;
    /**
     * The username of the account associated with the message.
     * @nullable
     */
    readonly Username?: string | null;
}
