/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { MetricReportOemActions } from './MetricReportOemActions';

/**
 * The available actions for this resource.
 * @version 1.5.2
 */
export interface MetricReportActions {
    /** The available OEM-specific actions for this resource. */
    Oem?: MetricReportOemActions;
}
