/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { ResourceOem } from './ResourceOem';

/**
 * Properties that capture a metric value and other associated information.
 * @version 1.5.2
 */
export interface MetricReportMetricValue {
    /**
     * The link to the metric definition for this metric.
     * @deprecated
     */
    readonly MetricDefinition?: OdataV4IdRef;
    /**
     * The metric definitions identifier that contains additional information for the source metric.
     * @nullable
     */
    readonly MetricId?: string | null;
    /**
     * The URI for the property from which this metric is derived.
     * @nullable
     */
    readonly MetricProperty?: string | null;
    /**
     * The metric value, as a string.
     * @nullable
     */
    readonly MetricValue?: string | null;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * The date and time when the metric is obtained.  A management application can establish a time series of metric data by retrieving the instances of metric value and sorting them according to their timestamp.
     * @nullable
     */
    readonly Timestamp?: string | null;
}
