/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Context } from './OdataV4Context';
import type { OdataV4Etag } from './OdataV4Etag';
import type { OdataV4Id } from './OdataV4Id';
import type { OdataV4Type } from './OdataV4Type';
import type { ResourceDescription } from './ResourceDescription';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { OdataV4Count } from './OdataV4Count';
import type { OdataV4NextLink } from './OdataV4NextLink';
import type { ResourceName } from './ResourceName';
import type { ResourceOem } from './ResourceOem';

/**
 * The collection of `MetricReport` resource instances.
 */
export interface MetricReportCollection {
    '@odata.context'?: OdataV4Context;
    '@odata.etag'?: OdataV4Etag;
    '@odata.id': OdataV4Id;
    '@odata.type': OdataV4Type;
    /** @nullable */
    readonly Description?: ResourceDescription;
    /** The members of this collection. */
    readonly Members: readonly OdataV4IdRef[];
    'Members@odata.count': OdataV4Count;
    'Members@odata.nextLink'?: OdataV4NextLink;
    readonly Name: ResourceName;
    /** The OEM extension property. */
    Oem?: ResourceOem;
}
