/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Context } from './OdataV4Context';
import type { OdataV4Etag } from './OdataV4Etag';
import type { OdataV4Id } from './OdataV4Id';
import type { OdataV4Type } from './OdataV4Type';
import type { MetricReportActions } from './MetricReportActions';
import type { ResourceDescription } from './ResourceDescription';
import type { ResourceId } from './ResourceId';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { MetricReportMetricValue } from './MetricReportMetricValue';
import type { ResourceName } from './ResourceName';
import type { ResourceOem } from './ResourceOem';

/**
 * The `MetricReport` schema represents a set of collected metrics.
 * @version 1.5.2
 */
export interface MetricReport {
    '@odata.context'?: OdataV4Context;
    '@odata.etag'?: OdataV4Etag;
    '@odata.id': OdataV4Id;
    '@odata.type': OdataV4Type;
    /** The available actions for this resource. */
    Actions?: MetricReportActions;
    /** A context can be supplied at subscription time.  This property is the context value supplied by the subscriber. */
    readonly Context?: string;
    /** @nullable */
    readonly Description?: ResourceDescription;
    readonly Id: ResourceId;
    /** The link to the definition of this metric report. */
    readonly MetricReportDefinition?: OdataV4IdRef;
    /** An array of metric values for the metered items of this metric report. */
    MetricValues?: MetricReportMetricValue[];
    readonly Name: ResourceName;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * The current sequence identifier for this metric report.
     * @deprecated
     */
    readonly ReportSequence?: string;
    /**
     * The time associated with the metric report in its entirety.  The time of the metric report can be relevant when the time of individual metrics are minimally different.
     * @nullable
     */
    readonly Timestamp?: string | null;
}
