/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { Message } from './Message';

/**
 * The properties that describe an error from a Redfish service.
 */
export type RedfishErrorError = {
    /** An array of messages describing one or more error messages. */
    '@Message.ExtendedInfo'?: Message[];
    /** A string indicating a specific `MessageId` from a message registry. */
    readonly code: string;
    /** A human-readable error message corresponding to the message in a message registry. */
    readonly message: string;
};
