/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { RedfishErrorError } from './RedfishErrorError';

/**
 * The error payload from a Redfish service.
 */
export interface RedfishError {
    /** The properties that describe an error from a Redfish service. */
    error: RedfishErrorError;
}
