/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Id } from './OdataV4Id';
import type { RedundancyActions } from './RedundancyActions';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { OdataV4Count } from './OdataV4Count';
import type { RedundancyMode } from './RedundancyMode';
import type { ResourceOem } from './ResourceOem';
import type { ResourceStatus } from './ResourceStatus';

/**
 * The common redundancy definition and structure used in other Redfish schemas.
 * @version 1.7.0
 */
export interface Redundancy {
    '@odata.id': OdataV4Id;
    /** The available actions for this resource. */
    Actions?: RedundancyActions;
    /** The links to the active members included in this redundancy set. */
    readonly ActiveRedundancySet?: readonly OdataV4IdRef[];
    'ActiveRedundancySet@odata.count'?: OdataV4Count;
    /**
     * The maximum number of members allowable for this particular redundancy group.
     * @nullable
     */
    readonly MaxNumSupported?: number | null;
    /** The unique identifier for the member within an array. */
    readonly MemberId: string;
    /**
     * The minimum number of members needed for this group to remain operational or functional.
     * @nullable
     */
    readonly MinNumNeeded: number | null;
    /**
     * The minimum number of members needed for this group to be redundant.
     * @nullable
     */
    readonly MinNumNeededForFaultTolerance?: number | null;
    /**
     * The redundancy mode of the group.
     * @nullable
     */
    Mode: RedundancyMode;
    /** The name of the resource or array member. */
    readonly Name: string;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * An indication of whether redundancy is enabled.
     * @nullable
     */
    RedundancyEnabled?: boolean | null;
    /** The links to components of this redundancy set. */
    readonly RedundancySet: readonly OdataV4IdRef[];
    'RedundancySet@odata.count'?: OdataV4Count;
    /** The status and health of the resource and its subordinate or dependent resources. */
    Status: ResourceStatus;
}
