/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

export type ResourceResetType =
    (typeof ResourceResetType)[keyof typeof ResourceResetType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourceResetType = {
    /** Turn on the unit. */
    On: 'On',
    /** Turn off the unit immediately (non-graceful shutdown). */
    ForceOff: 'ForceOff',
    /** Shut down gracefully and power off. */
    GracefulShutdown: 'GracefulShutdown',
    /** Shut down gracefully and restart the unit. */
    GracefulRestart: 'GracefulRestart',
    /** Shut down immediately and non-gracefully and restart the unit. */
    ForceRestart: 'ForceRestart',
    /** Generate a diagnostic interrupt, which is usually an NMI on x86 systems, to stop normal operations, complete diagnostic actions, and, typically, halt the system. */
    Nmi: 'Nmi',
    /** Turn on the unit immediately. */
    ForceOn: 'ForceOn',
    /** Simulate the pressing of the physical power button on this unit. */
    PushPowerButton: 'PushPowerButton',
    /** Power cycle the unit immediately (non-graceful).  Behaves like a power removal, followed by a power restore to the resource. */
    PowerCycle: 'PowerCycle',
    /** Write the state of the unit to disk before powering off.  This allows for the state to be restored when powered back on. */
    Suspend: 'Suspend',
    /** Pause execution on the unit but do not remove power.  This is typically a feature of virtual machine hypervisors. */
    Pause: 'Pause',
    /** Resume execution on the paused unit.  This is typically a feature of virtual machine hypervisors. */
    Resume: 'Resume',
    /** Full power cycle the unit immediately (non-graceful).  Behaves like removing utility lines, followed by restoring utility lines to the resource. */
    FullPowerCycle: 'FullPowerCycle',
} as const;
