/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

export type ResourcePowerState =
    (typeof ResourcePowerState)[keyof typeof ResourcePowerState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourcePowerState = {
    /** The resource is powered on. */
    On: 'On',
    /** The resource is powered off.  The components within the resource might continue to have AUX power. */
    Off: 'Off',
    /** A temporary state between off and on.  The components within the resource can take time to process the power on action. */
    PoweringOn: 'PoweringOn',
    /** A temporary state between on and off.  The components within the resource can take time to process the power off action. */
    PoweringOff: 'PoweringOff',
    /** The resource is paused. */
    Paused: 'Paused',
} as const;
