/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The `Sensor` schema describes a sensor and its properties.
 * @version 1.9.3
 */
export interface SensorExcerpt {
    /**
     * The link to the resource that provides the data for this sensor.
     * @nullable
     */
    readonly DataSourceUri?: string | null;
    /**
     * The sensor value.
     * @nullable
     */
    readonly Reading?: number | null;
}
