/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The `Sensor` schema describes a sensor and its properties.
 * @version 1.9.3
 */
export interface SensorEnergykWhExcerpt {
    /**
     * Apparent energy (kVAh).
     * @nullable
     */
    readonly ApparentkVAh?: number | null;
    /**
     * The link to the resource that provides the data for this sensor.
     * @nullable
     */
    readonly DataSourceUri?: string | null;
    /**
     * The total accumulation value for this sensor.
     * @nullable
     */
    readonly LifetimeReading?: number | null;
    /**
     * Reactive energy (kVARh).
     * @nullable
     */
    readonly ReactivekVARh?: number | null;
    /**
     * The sensor value.
     * @nullable
     */
    readonly Reading?: number | null;
    /**
     * The date and time when the time-based properties were last reset.
     * @nullable
     */
    readonly SensorResetTime?: string | null;
}
