/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { PhysicalContext } from './PhysicalContext';
import type { PhysicalContextPhysicalSubContext } from './PhysicalContextPhysicalSubContext';

/**
 * The `Sensor` schema describes a sensor and its properties.
 * @version 1.9.3
 */
export interface SensorFanArrayExcerpt {
    /**
     * The link to the resource that provides the data for this sensor.
     * @nullable
     */
    readonly DataSourceUri?: string | null;
    /**
     * The name of the device.
     * @nullable
     */
    readonly DeviceName?: string | null;
    /**
     * The area or device to which this sensor measurement applies.
     * @nullable
     */
    PhysicalContext?: PhysicalContext;
    /**
     * The usage or location within a device to which this sensor measurement applies.
     * @nullable
     */
    PhysicalSubContext?: PhysicalContextPhysicalSubContext;
    /**
     * The sensor value.
     * @nullable
     */
    readonly Reading?: number | null;
    /**
     * The rotational speed.
     * @nullable
     */
    readonly SpeedRPM?: number | null;
}
