/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The `Sensor` schema describes a sensor and its properties.
 * @version 1.9.3
 */
export interface SensorPowerExcerpt {
    /**
     * The product of voltage and current for an AC circuit, in volt-ampere units.
     * @nullable
     */
    readonly ApparentVA?: number | null;
    /**
     * The link to the resource that provides the data for this sensor.
     * @nullable
     */
    readonly DataSourceUri?: string | null;
    /**
     * The phase angle (degrees) between the current and voltage waveforms.
     * @minimum -90
     * @maximum 90
     * @nullable
     */
    readonly PhaseAngleDegrees?: number | null;
    /**
     * The power factor for this sensor.
     * @minimum -1
     * @maximum 1
     * @nullable
     */
    readonly PowerFactor?: number | null;
    /**
     * The square root of the difference term of squared apparent VA and squared power (Reading) for a circuit, in VAR units.
     * @nullable
     */
    readonly ReactiveVAR?: number | null;
    /**
     * The sensor value.
     * @nullable
     */
    readonly Reading?: number | null;
}
