/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { TaskServiceDeleteAllCompletedTasks } from './TaskServiceDeleteAllCompletedTasks';
import type { TaskServiceOemActions } from './TaskServiceOemActions';

/**
 * The available actions for this resource.
 * @version 1.3.0
 */
export interface TaskServiceActions {
    '#TaskService.DeleteAllCompletedTasks'?: TaskServiceDeleteAllCompletedTasks;
    /** The available OEM-specific actions for this resource. */
    Oem?: TaskServiceOemActions;
}
