/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The HTTP and JSON payload details for this Task.
 * @version 1.7.4
 */
export interface TaskPayload {
    /** An array of HTTP headers that this task includes. */
    readonly HttpHeaders?: readonly string[];
    /** The HTTP operation to perform to execute this task. */
    readonly HttpOperation?: string;
    /** The JSON payload to use in the execution of this task. */
    readonly JsonBody?: string;
    /** The URI of the target for this task. */
    readonly TargetUri?: string;
}
