/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.3.0
 */
export type TaskServiceOverWritePolicy =
    (typeof TaskServiceOverWritePolicy)[keyof typeof TaskServiceOverWritePolicy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskServiceOverWritePolicy = {
    /** Completed tasks are not automatically overwritten. */
    Manual: 'Manual',
    /** Oldest completed tasks are overwritten. */
    Oldest: 'Oldest',
} as const;
