/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.7.4
 */
export type TaskState = (typeof TaskState)[keyof typeof TaskState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskState = {
    /** A new task. */
    New: 'New',
    /** Task is starting. */
    Starting: 'Starting',
    /** Task is running normally. */
    Running: 'Running',
    /** Task has been suspended. */
    Suspended: 'Suspended',
    /** Task has been interrupted. */
    Interrupted: 'Interrupted',
    /** Task is pending and has not started. */
    Pending: 'Pending',
    /** Task is in the process of stopping. */
    Stopping: 'Stopping',
    /** Task was completed. */
    Completed: 'Completed',
    /** Task was terminated. */
    Killed: 'Killed',
    /** Task has stopped due to an exception condition. */
    Exception: 'Exception',
    /** Task is running as a service. */
    Service: 'Service',
    /** Task is in the process of being cancelled. */
    Cancelling: 'Cancelling',
    /** Task has been cancelled by an operator or internal process. */
    Cancelled: 'Cancelled',
} as const;
