/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The available OEM-specific actions for this resource.
 * @version 1.7.4
 */
export interface TaskOemActions {
    [key: string]: unknown;
}
