/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { OdataV4Count } from './OdataV4Count';
import type { ResourceOem } from './ResourceOem';

/**
 * The links to other resources that are related to this resource.
 * @version 1.7.4
 */
export interface TaskLinks {
    /** An array of URIs referencing the resources created as the result of the operation that produced this task. */
    readonly CreatedResources?: readonly OdataV4IdRef[];
    'CreatedResources@odata.count'?: OdataV4Count;
    /** The OEM extension property. */
    Oem?: ResourceOem;
}
