/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Context } from './OdataV4Context';
import type { OdataV4Etag } from './OdataV4Etag';
import type { OdataV4Id } from './OdataV4Id';
import type { OdataV4Type } from './OdataV4Type';
import type { TaskServiceActions } from './TaskServiceActions';
import type { TaskServiceOverWritePolicy } from './TaskServiceOverWritePolicy';
import type { ResourceDescription } from './ResourceDescription';
import type { ResourceId } from './ResourceId';
import type { ResourceName } from './ResourceName';
import type { ResourceOem } from './ResourceOem';
import type { ResourceStatus } from './ResourceStatus';
import type { OdataV4IdRef } from './OdataV4IdRef';

/**
 * The `TaskService` schema describes a task service that enables management of long-duration operations, includes the properties for the task service itself, and has links to the resource collection of tasks.
 * @version 1.3.0
 */
export interface TaskService {
    '@odata.context'?: OdataV4Context;
    '@odata.etag'?: OdataV4Etag;
    '@odata.id': OdataV4Id;
    '@odata.type': OdataV4Type;
    /** The available actions for this resource. */
    Actions?: TaskServiceActions;
    /** The overwrite policy for completed tasks.  This property indicates if the task service overwrites completed task information. */
    readonly CompletedTaskOverWritePolicy?: TaskServiceOverWritePolicy;
    /**
     * The current date and time, with UTC offset, setting that the task service uses.
     * @nullable
     */
    readonly DateTime?: string | null;
    /** @nullable */
    readonly Description?: ResourceDescription;
    readonly Id: ResourceId;
    /** An indication of whether a task state change sends an event. */
    readonly LifeCycleEventOnTaskStateChange?: boolean;
    readonly Name: ResourceName;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * An indication of whether this service is enabled.
     * @nullable
     */
    ServiceEnabled?: boolean | null;
    /** The status and health of the resource and its subordinate or dependent resources. */
    Status?: ResourceStatus;
    /**
     * The number of minutes after which a completed task is deleted by the service.
     * @minimum 1
     */
    TaskAutoDeleteTimeoutMinutes?: number;
    /**
     * The number of seconds after reading a task monitor for a completed task until the service deletes the task monitor.
     * @minimum 0
     * @nullable
     */
    TaskMonitorAutoExpirySeconds?: number | null;
    /** The links to the collection of tasks. */
    readonly Tasks?: OdataV4IdRef;
}
