/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * An operation to perform over the sample.
 * @version 1.4.1
 */
export type TelemetryServiceCollectionFunction =
    (typeof TelemetryServiceCollectionFunction)[keyof typeof TelemetryServiceCollectionFunction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TelemetryServiceCollectionFunction = {
    /** An averaging function. */
    Average: 'Average',
    /** A maximum function. */
    Maximum: 'Maximum',
    /** A minimum function. */
    Minimum: 'Minimum',
    /** A summation function. */
    Summation: 'Summation',
} as const;
