/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { TelemetryServiceClearMetricReports } from './TelemetryServiceClearMetricReports';
import type { TelemetryServiceClearTelemetryData } from './TelemetryServiceClearTelemetryData';
import type { TelemetryServiceCollectTelemetryData } from './TelemetryServiceCollectTelemetryData';
import type { TelemetryServiceResetMetricReportDefinitionsToDefaults } from './TelemetryServiceResetMetricReportDefinitionsToDefaults';
import type { TelemetryServiceResetTriggersToDefaults } from './TelemetryServiceResetTriggersToDefaults';
import type { TelemetryServiceSubmitTestMetricReport } from './TelemetryServiceSubmitTestMetricReport';
import type { TelemetryServiceOemActions } from './TelemetryServiceOemActions';

/**
 * The available actions for this resource.
 * @version 1.4.1
 */
export interface TelemetryServiceActions {
    '#TelemetryService.ClearMetricReports'?: TelemetryServiceClearMetricReports;
    '#TelemetryService.ClearTelemetryData'?: TelemetryServiceClearTelemetryData;
    '#TelemetryService.CollectTelemetryData'?: TelemetryServiceCollectTelemetryData;
    '#TelemetryService.ResetMetricReportDefinitionsToDefaults'?: TelemetryServiceResetMetricReportDefinitionsToDefaults;
    '#TelemetryService.ResetTriggersToDefaults'?: TelemetryServiceResetTriggersToDefaults;
    '#TelemetryService.SubmitTestMetricReport'?: TelemetryServiceSubmitTestMetricReport;
    /** The available OEM-specific actions for this resource. */
    Oem?: TelemetryServiceOemActions;
}
