/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The action to collect the telemetry data from a device or service.  When the telemetry data is collected, a new telemetry data resource will be created.
 * @version 1.4.1
 */
export interface TelemetryServiceCollectTelemetryData {
    /** Link to invoke action */
    target?: string;
    /** Friendly action name */
    title?: string;
}
