/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * This action generates a metric report.
 * @version 1.4.1
 */
export interface TelemetryServiceSubmitTestMetricReport {
    /** Link to invoke action */
    target?: string;
    /** Friendly action name */
    title?: string;
}
