/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Context } from './OdataV4Context';
import type { OdataV4Etag } from './OdataV4Etag';
import type { OdataV4Id } from './OdataV4Id';
import type { OdataV4Type } from './OdataV4Type';
import type { TelemetryServiceActions } from './TelemetryServiceActions';
import type { ResourceDescription } from './ResourceDescription';
import type { ResourceId } from './ResourceId';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { ResourceName } from './ResourceName';
import type { ResourceOem } from './ResourceOem';
import type { ResourceStatus } from './ResourceStatus';
import type { TelemetryServiceCollectionFunction } from './TelemetryServiceCollectionFunction';
import type { TelemetryDataTypes } from './TelemetryDataTypes';

/**
 * The `TelemetryService` schema describes a telemetry service.  The telemetry service is used for collecting and reporting metric data within the Redfish service.
 * @version 1.4.1
 */
export interface TelemetryService {
    '@odata.context'?: OdataV4Context;
    '@odata.etag'?: OdataV4Etag;
    '@odata.id': OdataV4Id;
    '@odata.type': OdataV4Type;
    /** The available actions for this resource. */
    Actions?: TelemetryServiceActions;
    /** @nullable */
    readonly Description?: ResourceDescription;
    readonly Id: ResourceId;
    /** The link to a log service that the telemetry service uses.  This service can be a dedicated log service or a pointer to a log service under another resource, such as a manager. */
    readonly LogService?: OdataV4IdRef;
    /**
     * The maximum number of metric reports that this service supports.
     * @nullable
     */
    readonly MaxReports?: number | null;
    /** The link to the collection of metric definitions. */
    readonly MetricDefinitions?: OdataV4IdRef;
    /** The link to the collection of metric report definitions. */
    readonly MetricReportDefinitions?: OdataV4IdRef;
    /** The link to the collection of metric reports. */
    readonly MetricReports?: OdataV4IdRef;
    /**
     * The minimum time interval between gathering metric data that this service allows.
     * @nullable
     * @pattern ^P(\d+D)?(T(\d+H)?(\d+M)?(\d+(.\d+)?S)?)?$
     */
    readonly MinCollectionInterval?: string | null;
    readonly Name: ResourceName;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * An indication of whether this service is enabled.
     * @nullable
     */
    ServiceEnabled?: boolean | null;
    /** The status and health of the resource and its subordinate or dependent resources. */
    Status?: ResourceStatus;
    /** The functions that can be performed over each metric. */
    readonly SupportedCollectionFunctions?: readonly TelemetryServiceCollectionFunction[];
    /** A list of supported OEM-defined telemetry data types. */
    readonly SupportedOEMTelemetryDataTypes?: readonly (string | null)[];
    /** A list of supported telemetry data types. */
    readonly SupportedTelemetryDataTypes?: readonly TelemetryDataTypes[];
    /** The link to the collection of data telemetry. */
    readonly TelemetryData?: OdataV4IdRef;
    /** The link to the collection of triggers that apply to metrics. */
    readonly Triggers?: OdataV4IdRef;
}
