/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The action to reset the metric report definitions to factory defaults.
 * @version 1.4.1
 */
export interface TelemetryServiceResetMetricReportDefinitionsToDefaults {
    /** Link to invoke action */
    target?: string;
    /** Friendly action name */
    title?: string;
}
