/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

export type TelemetryDataTypes =
    (typeof TelemetryDataTypes)[keyof typeof TelemetryDataTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TelemetryDataTypes = {
    /** OEM telemetry data. */
    OEM: 'OEM',
} as const;
