/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.17.0
 */
export type UpdateServiceApplyTime =
    (typeof UpdateServiceApplyTime)[keyof typeof UpdateServiceApplyTime];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateServiceApplyTime = {
    /** Apply immediately. */
    Immediate: 'Immediate',
    /** Apply on a reset. */
    OnReset: 'OnReset',
    /** Apply during an administrator-specified maintenance window. */
    AtMaintenanceWindowStart: 'AtMaintenanceWindowStart',
    /** Apply after a reset but within an administrator-specified maintenance window. */
    InMaintenanceWindowOnReset: 'InMaintenanceWindowOnReset',
    /** Apply when the `StartUpdate` action of the update service is invoked. */
    OnStartUpdateRequest: 'OnStartUpdateRequest',
    /** Apply when the target for the software update is reset.  Targets include devices, services, and systems. */
    OnTargetReset: 'OnTargetReset',
} as const;
