/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { UpdateServiceApplyTime } from './UpdateServiceApplyTime';

/**
 * The settings for when to apply `HttpPushUri`-provided software.
 * @version 1.17.0
 */
export interface UpdateServiceHttpPushUriApplyTime {
    /** The time when to apply the `HttpPushUri`-provided software update. */
    ApplyTime?: UpdateServiceApplyTime;
    /**
     * The expiry time, in seconds, of the maintenance window.
     * @minimum 0
     */
    MaintenanceWindowDurationInSeconds?: number;
    /** The start time of a maintenance window. */
    MaintenanceWindowStartTime?: string;
}
