/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { UpdateServiceHttpPushUriApplyTime } from './UpdateServiceHttpPushUriApplyTime';

/**
 * The settings for `HttpPushUri`-provided software updates.
 * @version 1.17.0
 */
export interface UpdateServiceHttpPushUriOptions {
    /** An indication of whether the service should bypass update policies when applying the `HttpPushUri`-provided image. */
    ForceUpdate?: boolean;
    /** The settings for when to apply `HttpPushUri`-provided firmware. */
    HttpPushUriApplyTime?: UpdateServiceHttpPushUriApplyTime;
}
