/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * This action starts updating all images that have been previously invoked using an `OperationApplyTime` value of `OnStartUpdateRequest`.
 * @version 1.17.0
 */
export interface UpdateServiceStartUpdate {
    /** Link to invoke action */
    target?: string;
    /** Friendly action name */
    title?: string;
}
