/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { UpdateServiceActivate } from './UpdateServiceActivate';
import type { UpdateServiceGenerateSSHIdentityKeyPair } from './UpdateServiceGenerateSSHIdentityKeyPair';
import type { UpdateServiceRemoveSSHIdentityKeyPair } from './UpdateServiceRemoveSSHIdentityKeyPair';
import type { UpdateServiceSimpleUpdate } from './UpdateServiceSimpleUpdate';
import type { UpdateServiceStartUpdate } from './UpdateServiceStartUpdate';
import type { UpdateServiceOemActions } from './UpdateServiceOemActions';

/**
 * The available actions for this resource.
 * @version 1.17.0
 */
export interface UpdateServiceActions {
    '#UpdateService.Activate'?: UpdateServiceActivate;
    '#UpdateService.GenerateSSHIdentityKeyPair'?: UpdateServiceGenerateSSHIdentityKeyPair;
    '#UpdateService.RemoveSSHIdentityKeyPair'?: UpdateServiceRemoveSSHIdentityKeyPair;
    '#UpdateService.SimpleUpdate'?: UpdateServiceSimpleUpdate;
    '#UpdateService.StartUpdate'?: UpdateServiceStartUpdate;
    /** The available OEM-specific actions for this resource. */
    Oem?: UpdateServiceOemActions;
}
