/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * This action generates a new SSH identity key-pair to be used with the `UpdateService` resource.  The generated public key is stored in the `Key` resource referenced by the `PublicIdentitySSHKey` property.  Any existing key-pair is deleted and replaced by the new key-pair.
 * @version 1.17.0
 */
export interface UpdateServiceGenerateSSHIdentityKeyPair {
    /** Link to invoke action */
    target?: string;
    /** Friendly action name */
    title?: string;
}
