/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.17.0
 */
export type UpdateServiceSupportedUpdateImageFormatType =
    (typeof UpdateServiceSupportedUpdateImageFormatType)[keyof typeof UpdateServiceSupportedUpdateImageFormatType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateServiceSupportedUpdateImageFormatType = {
    /** A PLDM for Firmware Update Specification v1.0 image. */
    PLDMv1_0: 'PLDMv1_0',
    /** A PLDM for Firmware Update Specification v1.1 image. */
    PLDMv1_1: 'PLDMv1_1',
    /** A PLDM for Firmware Update Specification v1.2 image. */
    PLDMv1_2: 'PLDMv1_2',
    /** A PLDM for Firmware Update Specification v1.3 image. */
    PLDMv1_3: 'PLDMv1_3',
    /** The image conforms to the capsule format described in the UEFI Specification. */
    UEFICapsule: 'UEFICapsule',
    /** A vendor-defined image. */
    VendorDefined: 'VendorDefined',
} as const;
