/**
 * Minimal endpoints file - contains only exports used by the app.
 *
 * Generated by: scripts/api/generate-dist-endpoints.ts
 * Hooks: 19
 * Bare functions: 8
 * Total exports: 75
 *
 * For full API, use redfish.gen.ts (development only)
 */

/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/vue-query';
import type {
    DataTag,
    InfiniteData,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UseInfiniteQueryOptions,
    UseInfiniteQueryReturnType,
    UseMutationOptions,
    UseMutationReturnType,
    UseQueryOptions,
    UseQueryReturnType,
} from '@tanstack/vue-query';

import { computed, unref } from 'vue';
import type { MaybeRef } from 'vue';

import type {
    AccelerationFunction,
    AccelerationFunctionCollection,
    AccountService,
    AddressPool,
    AddressPoolCollection,
    Aggregate,
    AggregateAddElementsRequestBody,
    AggregateCollection,
    AggregateRemoveElementsRequestBody,
    AggregateResetRequestBody,
    AggregateSetDefaultBootOrderRequestBody,
    AggregationService,
    AggregationServiceResetRequestBody,
    AggregationServiceSetDefaultBootOrderRequestBody,
    AggregationSource,
    AggregationSourceCollection,
    AggregationSourceGenerateSSHIdentityKeyPairRequestBody,
    AggregationSourceRemoveSSHIdentityKeyPairRequestBody,
    AllowDeny,
    AllowDenyCollection,
    Application,
    ApplicationCollection,
    ApplicationResetRequestBody,
    Assembly,
    AutomationInstrumentation,
    AutomationNode,
    AutomationNodeCollection,
    AutomationNodeResetRequestBody,
    AutomationNodeSendTriggerRequestBody,
    AutomationNodeStartRequestBody,
    AutomationNodeStopRequestBody,
    AutomationNodeWaitRequestBody,
    Battery,
    BatteryCalibrateRequestBody,
    BatteryCollection,
    BatteryMetrics,
    BatteryResetRequestBody,
    BatterySelfTestRequestBody,
    Bios,
    BiosChangePasswordRequestBody,
    BiosResetBiosRequestBody,
    BootOption,
    BootOptionCollection,
    CXLLogicalDevice,
    CXLLogicalDeviceCollection,
    CXLLogicalDeviceDisablePassphraseRequestBody,
    CXLLogicalDeviceFreezeSecurityStateRequestBody,
    CXLLogicalDevicePassphraseSecureEraseRequestBody,
    CXLLogicalDeviceSetPassphraseRequestBody,
    CXLLogicalDeviceUnlockRequestBody,
    Cable,
    CableCollection,
    Certificate,
    CertificateCollection,
    CertificateEnrollment,
    CertificateEnrollmentCollection,
    CertificateForceAutomaticRenewRequestBody,
    CertificateLocations,
    CertificateRekeyRequestBody,
    CertificateRekeyResponse,
    CertificateRenewRequestBody,
    CertificateRenewResponse,
    CertificateService,
    CertificateServiceGenerateCSRRequestBody,
    CertificateServiceGenerateCSRResponse,
    CertificateServiceReplaceCertificateRequestBody,
    Chassis,
    ChassisCollection,
    ChassisResetRequestBody,
    Circuit,
    CircuitBreakerControlRequestBody,
    CircuitCollection,
    CircuitPowerControlRequestBody,
    CircuitResetMetricsRequestBody,
    ComponentIntegrity,
    ComponentIntegrityCollection,
    ComponentIntegritySPDMGetSignedMeasurementsRequestBody,
    ComponentIntegritySPDMGetSignedMeasurementsResponse,
    ComponentIntegrityTPMGetSignedMeasurementsRequestBody,
    ComponentIntegrityTPMGetSignedMeasurementsResponse,
    CompositionReservation,
    CompositionReservationCollection,
    CompositionService,
    CompositionServiceComposeRequestBody,
    CompositionServiceComposeResponse,
    ComputerSystem,
    ComputerSystemAddResourceBlockRequestBody,
    ComputerSystemCollection,
    ComputerSystemDecommissionRequestBody,
    ComputerSystemExportConfigurationRequestBody,
    ComputerSystemRemoveResourceBlockRequestBody,
    ComputerSystemResetRequestBody,
    ComputerSystemSetDefaultBootOrderRequestBody,
    Connection,
    ConnectionAddVolumeInfoRequestBody,
    ConnectionCollection,
    ConnectionMethod,
    ConnectionMethodCollection,
    ConnectionRemoveVolumeInfoRequestBody,
    Container,
    ContainerCollection,
    ContainerImage,
    ContainerImageCollection,
    ContainerResetRequestBody,
    Control,
    ControlCollection,
    ControlResetToDefaultsRequestBody,
    CoolantConnector,
    CoolantConnectorCollection,
    CoolantConnectorValveControlRequestBody,
    CoolingLoop,
    CoolingLoopCollection,
    CoolingUnit,
    CoolingUnitCollection,
    CoolingUnitExportConfigurationRequestBody,
    CoolingUnitSetModeRequestBody,
    Drive,
    DriveCollection,
    DriveFreezePersonalityRequestBody,
    DriveGetPersonalityNonceRequestBody,
    DriveGetPersonalityNonceResponse,
    DriveMetrics,
    DriveResetRequestBody,
    DriveRevertPersonalitiesToDefaultsRequestBody,
    DriveRevertToOriginalFactoryStateRequestBody,
    DriveSecureEraseRequestBody,
    DriveSetPersonalityKeyRequestBody,
    DriveUnfreezePersonalityRequestBody,
    Endpoint,
    EndpointCollection,
    EndpointGroup,
    EndpointGroupCollection,
    EnvironmentMetrics,
    EnvironmentMetricsResetMetricsRequestBody,
    EnvironmentMetricsResetToDefaultsRequestBody,
    EthernetInterface,
    EthernetInterfaceCollection,
    EventDestination,
    EventDestinationCollection,
    EventDestinationResumeSubscriptionRequestBody,
    EventDestinationSuspendSubscriptionRequestBody,
    EventService,
    EventServiceSubmitTestEventRequestBody,
    EventServiceTestEventSubscriptionRequestBody,
    ExternalAccountProvider,
    ExternalAccountProviderCollection,
    Fabric,
    FabricAdapter,
    FabricAdapterCollection,
    FabricCollection,
    Facility,
    FacilityCollection,
    Fan,
    FanCollection,
    Filter,
    FilterCollection,
    Getodata200,
    GraphicsController,
    GraphicsControllerCollection,
    Heater,
    HeaterCollection,
    HeaterMetrics,
    HeaterMetricsResetMetricsRequestBody,
    HostInterface,
    HostInterfaceCollection,
    Job,
    JobCancelRequestBody,
    JobCollection,
    JobDocument,
    JobDocumentCollection,
    JobDocumentSubmitJobRequestBody,
    JobExecutor,
    JobExecutorCollection,
    JobForceStartRequestBody,
    JobInvalidateRequestBody,
    JobResubmitRequestBody,
    JobResumeRequestBody,
    JobService,
    JobServiceCancelAllJobsRequestBody,
    JobSuspendRequestBody,
    JobValidateRequestBody,
    JsonSchemaFile,
    JsonSchemaFileCollection,
    Key,
    KeyCollection,
    KeyPolicy,
    KeyPolicyCollection,
    KeyService,
    LeakDetection,
    LeakDetector,
    LeakDetectorCollection,
    License,
    LicenseCollection,
    LicenseService,
    LicenseServiceInstallRequestBody,
    LogEntry,
    LogEntryCollection,
    LogService,
    LogServiceClearLogRequestBody,
    LogServiceCollectDiagnosticDataRequestBody,
    LogServiceCollection,
    LogServiceDownloadRawLogRequestBody,
    LogServiceDownloadRawLogResponse,
    LogServicePushDiagnosticDataRequestBody,
    Manager,
    ManagerAccount,
    ManagerAccountChangePasswordRequestBody,
    ManagerAccountClearSecretKeyRequestBody,
    ManagerAccountCollection,
    ManagerAccountGenerateSecretKeyRequestBody,
    ManagerAccountGenerateSecretKeyResponse,
    ManagerAccountVerifyTimeBasedOneTimePasswordRequestBody,
    ManagerCollection,
    ManagerDiagnosticData,
    ManagerDiagnosticDataResetMetricsRequestBody,
    ManagerForceFailoverRequestBody,
    ManagerModifyRedundancySetRequestBody,
    ManagerNetworkProtocol,
    ManagerResetRequestBody,
    ManagerResetToDefaultsRequestBody,
    ManagerUpdateSecurityModeRequestBody,
    MediaController,
    MediaControllerCollection,
    MediaControllerResetRequestBody,
    Memory,
    MemoryChunks,
    MemoryChunksCollection,
    MemoryCollection,
    MemoryDisableMasterPassphraseRequestBody,
    MemoryDisablePassphraseRequestBody,
    MemoryDomain,
    MemoryDomainCollection,
    MemoryFreezeSecurityStateRequestBody,
    MemoryInjectPersistentPoisonRequestBody,
    MemoryMetrics,
    MemoryMetricsClearCurrentPeriodRequestBody,
    MemoryOverwriteUnitRequestBody,
    MemoryRegion,
    MemoryRegionCollection,
    MemoryResetRequestBody,
    MemoryResetToDefaultsRequestBody,
    MemoryScanMediaRequestBody,
    MemorySecureEraseUnitRequestBody,
    MemorySetMasterPassphraseRequestBody,
    MemorySetPassphraseRequestBody,
    MemoryUnlockUnitRequestBody,
    MessageRegistryFile,
    MessageRegistryFileCollection,
    MetricDefinition,
    MetricDefinitionCollection,
    MetricReport,
    MetricReportCollection,
    MetricReportDefinition,
    MetricReportDefinitionCollection,
    NetworkAdapter,
    NetworkAdapterCollection,
    NetworkAdapterMetrics,
    NetworkAdapterMetricsResetMetricsRequestBody,
    NetworkAdapterResetRequestBody,
    NetworkAdapterResetSettingsToDefaultRequestBody,
    NetworkDeviceFunction,
    NetworkDeviceFunctionCollection,
    NetworkDeviceFunctionMetrics,
    NetworkDeviceFunctionMetricsResetMetricsRequestBody,
    NetworkInterface,
    NetworkInterfaceCollection,
    NetworkPort,
    NetworkPortCollection,
    OperatingConfig,
    OperatingConfigCollection,
    OperatingSystem,
    OutboundConnection,
    OutboundConnectionCollection,
    Outlet,
    OutletCollection,
    OutletGroup,
    OutletGroupCollection,
    OutletGroupPowerControlRequestBody,
    OutletGroupResetMetricsRequestBody,
    OutletPowerControlRequestBody,
    OutletResetMetricsRequestBody,
    PCIeDevice,
    PCIeDeviceCollection,
    PCIeFunction,
    PCIeFunctionCollection,
    PCIeSlots,
    Port,
    PortCollection,
    PortMetrics,
    PortMetricsResetMetricsRequestBody,
    PortResetPPBRequestBody,
    PortResetRequestBody,
    Power,
    PowerDistribution,
    PowerDistributionCollection,
    PowerDistributionExportConfigurationRequestBody,
    PowerDistributionMetrics,
    PowerDistributionMetricsResetMetricsRequestBody,
    PowerDistributionTransferControlRequestBody,
    PowerDomain,
    PowerDomainCollection,
    PowerEquipment,
    PowerSubsystem,
    PowerSupply,
    PowerSupplyCollection,
    PowerSupplyMetrics,
    PowerSupplyMetricsResetMetricsRequestBody,
    PowerSupplyResetRequestBody,
    Processor,
    ProcessorCollection,
    ProcessorMetrics,
    ProcessorMetricsClearCurrentPeriodRequestBody,
    ProcessorResetRequestBody,
    ProcessorResetToDefaultsRequestBody,
    Pump,
    PumpCollection,
    PumpSetModeRequestBody,
    RedfishError,
    RegisteredClient,
    RegisteredClientCollection,
    Reservoir,
    ReservoirCollection,
    ResourceBlock,
    ResourceBlockCollection,
    Role,
    RoleCollection,
    RouteEntry,
    RouteEntryCollection,
    RouteSetEntry,
    RouteSetEntryCollection,
    SecureBoot,
    SecureBootDatabase,
    SecureBootDatabaseCollection,
    SecureBootDatabaseResetKeysRequestBody,
    SecureBootResetKeysRequestBody,
    SecurityPolicy,
    Sensor,
    SensorCollection,
    SensorResetMetricsRequestBody,
    SensorResetToDefaultsRequestBody,
    SerialInterface,
    SerialInterfaceCollection,
    ServiceConditions,
    ServiceRoot,
    Session,
    SessionCollection,
    SessionService,
    Signature,
    SignatureCollection,
    SimpleStorage,
    SimpleStorageCollection,
    SoftwareInventory,
    SoftwareInventoryActivateRequestBody,
    SoftwareInventoryCollection,
    Storage,
    StorageCollection,
    StorageController,
    StorageControllerAttachDetachNamespacesResponse,
    StorageControllerAttachNamespacesRequestBody,
    StorageControllerCollection,
    StorageControllerDetachNamespacesRequestBody,
    StorageControllerMetrics,
    StorageControllerResetRequestBody,
    StorageControllerSecurityReceiveRequestBody,
    StorageControllerSecurityReceiveResponse,
    StorageControllerSecuritySendRequestBody,
    StorageFreezePersonalityRequestBody,
    StorageGetPersonalityNonceRequestBody,
    StorageGetPersonalityNonceResponse,
    StorageImportForeignDrivesRequestBody,
    StorageMetrics,
    StorageRekeyExternalKeyRequestBody,
    StorageResetToDefaultsRequestBody,
    StorageRevertPersonalitiesToDefaultsRequestBody,
    StorageSetControllerPasswordRequestBody,
    StorageSetEncryptionKeyRequestBody,
    StorageSetPersonalityKeyRequestBody,
    StorageUnfreezePersonalityRequestBody,
    Switch,
    SwitchCollection,
    SwitchMetrics,
    SwitchMetricsClearCurrentPeriodRequestBody,
    SwitchResetRequestBody,
    Task,
    TaskCollection,
    TaskService,
    TaskServiceDeleteAllCompletedTasksRequestBody,
    TelemetryData,
    TelemetryDataCollection,
    TelemetryService,
    TelemetryServiceClearMetricReportsRequestBody,
    TelemetryServiceClearTelemetryDataRequestBody,
    TelemetryServiceCollectTelemetryDataRequestBody,
    TelemetryServiceCollectTelemetryDataResponse,
    TelemetryServiceResetMetricReportDefinitionsToDefaultsRequestBody,
    TelemetryServiceResetTriggersToDefaultsRequestBody,
    TelemetryServiceSubmitTestMetricReportRequestBody,
    Thermal,
    ThermalEquipment,
    ThermalMetrics,
    ThermalMetricsResetMetricsRequestBody,
    ThermalSubsystem,
    Triggers,
    TriggersCollection,
    TrustedComponent,
    TrustedComponentCollection,
    TrustedComponentTPMGetEventLogRequestBody,
    TrustedComponentTPMGetEventLogResponse,
    USBController,
    USBControllerCollection,
    UpdateService,
    UpdateServiceActivateRequestBody,
    UpdateServiceCapabilities,
    UpdateServiceGenerateSSHIdentityKeyPairRequestBody,
    UpdateServiceRemoveSSHIdentityKeyPairRequestBody,
    UpdateServiceSimpleUpdateRequestBody,
    UpdateServiceStartUpdateRequestBody,
    VCATEntry,
    VCATEntryCollection,
    VLanNetworkInterface,
    VLanNetworkInterfaceCollection,
    VirtualCXLSwitch,
    VirtualCXLSwitchCollection,
    VirtualMedia,
    VirtualMediaCollection,
    VirtualMediaEjectMediaRequestBody,
    VirtualMediaInsertMediaRequestBody,
    VirtualPCI2PCIBridge,
    VirtualPCI2PCIBridgeCollection,
    Volume,
    VolumeAssignReplicaTargetRequestBody,
    VolumeChangeRAIDLayoutRequestBody,
    VolumeCheckConsistencyRequestBody,
    VolumeCollection,
    VolumeCreateReplicaTargetRequestBody,
    VolumeForceEnableRequestBody,
    VolumeInitializeRequestBody,
    VolumeRemoveReplicaRelationshipRequestBody,
    VolumeResumeReplicationRequestBody,
    VolumeReverseReplicationRelationshipRequestBody,
    VolumeSplitReplicationRequestBody,
    VolumeSuspendReplicationRequestBody,
    Zone,
    ZoneAddEndpointRequestBody,
    ZoneCollection,
    ZoneRemoveEndpointRequestBody,
} from '../model';

import { apiInstance } from '../mutator/axios-instance';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
    (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
    [P in keyof T]-?: IfEquals<
        { [Q in P]: T[P] },
        { -readonly [Q in P]: T[P] },
        P
    >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
    k: infer I,
) => void
    ? I
    : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
    ? {
          [P in keyof Writable<T>]: T[P] extends object
              ? NonReadonly<NonNullable<T[P]>>
              : T[P];
      }
    : DistributeReadOnlyOverUnions<T>;


export const getServiceRoot = (signal?: AbortSignal) => {
    return apiInstance<ServiceRoot>({
        url: `/redfish/v1/`,
        method: 'GET',
        signal,
    });
};

export const getGetServiceRootQueryKey = () => {
    return [] as const;
};

export const getGetServiceRootQueryOptions = <
    TData = Awaited<ReturnType<typeof getServiceRoot>>,
    TError = RedfishError,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof getServiceRoot>>,
            TError,
            TData
        >
    >;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = getGetServiceRootQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getServiceRoot>>
    > = ({ signal }) => getServiceRoot(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getServiceRoot>>,
        TError,
        TData
    >;
};

export type GetServiceRootQueryResult = NonNullable<
    Awaited<ReturnType<typeof getServiceRoot>>
>;
export type GetServiceRootQueryError = RedfishError;

export function useGetServiceRoot<
    TData = Awaited<ReturnType<typeof getServiceRoot>>,
    TError = RedfishError,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getServiceRoot>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetServiceRootQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = unref(queryOptions).queryKey as DataTag<
        QueryKey,
        TData,
        TError
    >;

    return query;
}

export const getAccountService = (signal?: AbortSignal) => {
    return apiInstance<AccountService>({
        url: `/redfish/v1/AccountService`,
        method: 'GET',
        signal,
    });
};

export const getGetAccountServiceQueryKey = () => {
    return ['AccountService'] as const;
};

export const getGetAccountServiceQueryOptions = <
    TData = Awaited<ReturnType<typeof getAccountService>>,
    TError = RedfishError,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof getAccountService>>,
            TError,
            TData
        >
    >;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = getGetAccountServiceQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getAccountService>>
    > = ({ signal }) => getAccountService(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getAccountService>>,
        TError,
        TData
    >;
};

export type GetAccountServiceQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAccountService>>
>;
export type GetAccountServiceQueryError = RedfishError;

export function useGetAccountService<
    TData = Awaited<ReturnType<typeof getAccountService>>,
    TError = RedfishError,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAccountService>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetAccountServiceQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = unref(queryOptions).queryKey as DataTag<
        QueryKey,
        TData,
        TError
    >;

    return query;
}

export const patchAccountService = (
    accountService: MaybeRef<NonReadonly<AccountService>>,
) => {
    accountService = unref(accountService);

    return apiInstance<AccountService | Task | void>({
        url: `/redfish/v1/AccountService`,
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        data: accountService,
    });
};

export const getPatchAccountServiceMutationOptions = <
    TError = RedfishError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchAccountService>>,
        TError,
        { data: NonReadonly<AccountService> },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchAccountService>>,
    TError,
    { data: NonReadonly<AccountService> },
    TContext
> => {
    const mutationKey = ['patchAccountService'];
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          'mutationKey' in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchAccountService>>,
        { data: NonReadonly<AccountService> }
    > = (props) => {
        const { data } = props ?? {};

        return patchAccountService(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchAccountServiceMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchAccountService>>
>;
export type PatchAccountServiceMutationBody = NonReadonly<AccountService>;
export type PatchAccountServiceMutationError = RedfishError;

export const usePatchAccountService = <
    TError = RedfishError,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchAccountService>>,
            TError,
            { data: NonReadonly<AccountService> },
            TContext
        >;
    },
    queryClient?: QueryClient,
): UseMutationReturnType<
    Awaited<ReturnType<typeof patchAccountService>>,
    TError,
    { data: NonReadonly<AccountService> },
    TContext
> => {
    const mutationOptions = getPatchAccountServiceMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

export const getAccountServiceAccountById = (
    managerAccountId: MaybeRef<string | undefined | null>,
    signal?: AbortSignal,
) => {
    managerAccountId = unref(managerAccountId);

    return apiInstance<ManagerAccount>({
        url: `/redfish/v1/AccountService/Accounts/${encodeURIComponent(String(managerAccountId))}`,
        method: 'GET',
        signal,
    });
};

export const getGetAccountServiceAccountByIdQueryKey = (
    managerAccountId?: MaybeRef<string | undefined | null>,
) => {
    return ['AccountService', 'Accounts', managerAccountId] as const;
};

export const getGetAccountServiceAccountByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getAccountServiceAccountById>>,
    TError = RedfishError,
>(
    managerAccountId: MaybeRef<string | undefined | null>,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAccountServiceAccountById>>,
                TError,
                TData
            >
        >;
    },
) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = getGetAccountServiceAccountByIdQueryKey(managerAccountId);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getAccountServiceAccountById>>
    > = ({ signal }) => getAccountServiceAccountById(managerAccountId, signal);

    return {
        queryKey,
        queryFn,
        enabled: computed(() => !!unref(managerAccountId)),
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getAccountServiceAccountById>>,
        TError,
        TData
    >;
};

export type GetAccountServiceAccountByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAccountServiceAccountById>>
>;
export type GetAccountServiceAccountByIdQueryError = RedfishError;

export function useGetAccountServiceAccountById<
    TData = Awaited<ReturnType<typeof getAccountServiceAccountById>>,
    TError = RedfishError,
>(
    managerAccountId: MaybeRef<string | undefined | null>,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAccountServiceAccountById>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetAccountServiceAccountByIdQueryOptions(
        managerAccountId,
        options,
    );

    const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = unref(queryOptions).queryKey as DataTag<
        QueryKey,
        TData,
        TError
    >;

    return query;
}

export const getManagers = (signal?: AbortSignal) => {
    return apiInstance<ManagerCollection>({
        url: `/redfish/v1/Managers`,
        method: 'GET',
        signal,
    });
};

export const getGetManagersQueryKey = () => {
    return ['Managers'] as const;
};

export const getGetManagersQueryOptions = <
    TData = Awaited<ReturnType<typeof getManagers>>,
    TError = RedfishError,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof getManagers>>, TError, TData>
    >;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = getGetManagersQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getManagers>>> = ({
        signal,
    }) => getManagers(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getManagers>>,
        TError,
        TData
    >;
};

export type GetManagersQueryResult = NonNullable<
    Awaited<ReturnType<typeof getManagers>>
>;
export type GetManagersQueryError = RedfishError;

export function useGetManagers<
    TData = Awaited<ReturnType<typeof getManagers>>,
    TError = RedfishError,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getManagers>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetManagersQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = unref(queryOptions).queryKey as DataTag<
        QueryKey,
        TData,
        TError
    >;

    return query;
}

export const getManagersById = (
    managerId: MaybeRef<string | undefined | null>,
    signal?: AbortSignal,
) => {
    managerId = unref(managerId);

    return apiInstance<Manager>({
        url: `/redfish/v1/Managers/${encodeURIComponent(String(managerId))}`,
        method: 'GET',
        signal,
    });
};

export const getGetManagersByIdQueryKey = (
    managerId?: MaybeRef<string | undefined | null>,
) => {
    return ['Managers', managerId] as const;
};

export const getGetManagersByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getManagersById>>,
    TError = RedfishError,
>(
    managerId: MaybeRef<string | undefined | null>,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getManagersById>>,
                TError,
                TData
            >
        >;
    },
) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = getGetManagersByIdQueryKey(managerId);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getManagersById>>
    > = ({ signal }) => getManagersById(managerId, signal);

    return {
        queryKey,
        queryFn,
        enabled: computed(() => !!unref(managerId)),
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getManagersById>>,
        TError,
        TData
    >;
};

export type GetManagersByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getManagersById>>
>;
export type GetManagersByIdQueryError = RedfishError;

export function useGetManagersById<
    TData = Awaited<ReturnType<typeof getManagersById>>,
    TError = RedfishError,
>(
    managerId: MaybeRef<string | undefined | null>,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getManagersById>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetManagersByIdQueryOptions(managerId, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = unref(queryOptions).queryKey as DataTag<
        QueryKey,
        TData,
        TError
    >;

    return query;
}

export const getSystems = (signal?: AbortSignal) => {
    return apiInstance<ComputerSystemCollection>({
        url: `/redfish/v1/Systems`,
        method: 'GET',
        signal,
    });
};

export const getGetSystemsQueryKey = () => {
    return ['Systems'] as const;
};

export const getGetSystemsQueryOptions = <
    TData = Awaited<ReturnType<typeof getSystems>>,
    TError = RedfishError,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof getSystems>>, TError, TData>
    >;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = getGetSystemsQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSystems>>> = ({
        signal,
    }) => getSystems(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getSystems>>,
        TError,
        TData
    >;
};

export type GetSystemsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getSystems>>
>;
export type GetSystemsQueryError = RedfishError;

export function useGetSystems<
    TData = Awaited<ReturnType<typeof getSystems>>,
    TError = RedfishError,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getSystems>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetSystemsQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = unref(queryOptions).queryKey as DataTag<
        QueryKey,
        TData,
        TError
    >;

    return query;
}

export const getSystemsById = (
    computerSystemId: MaybeRef<string | undefined | null>,
    signal?: AbortSignal,
) => {
    computerSystemId = unref(computerSystemId);

    return apiInstance<ComputerSystem>({
        url: `/redfish/v1/Systems/${encodeURIComponent(String(computerSystemId))}`,
        method: 'GET',
        signal,
    });
};

export const getGetSystemsByIdQueryKey = (
    computerSystemId?: MaybeRef<string | undefined | null>,
) => {
    return ['Systems', computerSystemId] as const;
};

export const getGetSystemsByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getSystemsById>>,
    TError = RedfishError,
>(
    computerSystemId: MaybeRef<string | undefined | null>,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getSystemsById>>,
                TError,
                TData
            >
        >;
    },
) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = getGetSystemsByIdQueryKey(computerSystemId);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getSystemsById>>
    > = ({ signal }) => getSystemsById(computerSystemId, signal);

    return {
        queryKey,
        queryFn,
        enabled: computed(() => !!unref(computerSystemId)),
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getSystemsById>>,
        TError,
        TData
    >;
};

export type GetSystemsByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getSystemsById>>
>;
export type GetSystemsByIdQueryError = RedfishError;

export function useGetSystemsById<
    TData = Awaited<ReturnType<typeof getSystemsById>>,
    TError = RedfishError,
>(
    computerSystemId: MaybeRef<string | undefined | null>,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getSystemsById>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetSystemsByIdQueryOptions(
        computerSystemId,
        options,
    );

    const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = unref(queryOptions).queryKey as DataTag<
        QueryKey,
        TData,
        TError
    >;

    return query;
}

export const getSystemLogServices = (
    computerSystemId: MaybeRef<string | undefined | null>,
    signal?: AbortSignal,
) => {
    computerSystemId = unref(computerSystemId);

    return apiInstance<LogServiceCollection>({
        url: `/redfish/v1/Systems/${encodeURIComponent(String(computerSystemId))}/LogServices`,
        method: 'GET',
        signal,
    });
};

export const getGetSystemLogServicesQueryKey = (
    computerSystemId?: MaybeRef<string | undefined | null>,
) => {
    return ['Systems', computerSystemId, 'LogServices'] as const;
};

export const getGetSystemLogServicesQueryOptions = <
    TData = Awaited<ReturnType<typeof getSystemLogServices>>,
    TError = RedfishError,
>(
    computerSystemId: MaybeRef<string | undefined | null>,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getSystemLogServices>>,
                TError,
                TData
            >
        >;
    },
) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = getGetSystemLogServicesQueryKey(computerSystemId);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getSystemLogServices>>
    > = ({ signal }) => getSystemLogServices(computerSystemId, signal);

    return {
        queryKey,
        queryFn,
        enabled: computed(() => !!unref(computerSystemId)),
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getSystemLogServices>>,
        TError,
        TData
    >;
};

export const getSystemLogServiceEntries = (
    computerSystemId: MaybeRef<string | undefined | null>,
    logServiceId: MaybeRef<string | undefined | null>,
    signal?: AbortSignal,
) => {
    computerSystemId = unref(computerSystemId);
    logServiceId = unref(logServiceId);

    return apiInstance<LogEntryCollection>({
        url: `/redfish/v1/Systems/${encodeURIComponent(String(computerSystemId))}/LogServices/${encodeURIComponent(String(logServiceId))}/Entries`,
        method: 'GET',
        signal,
    });
};

export const getGetSystemLogServiceEntriesQueryKey = (
    computerSystemId?: MaybeRef<string | undefined | null>,
    logServiceId?: MaybeRef<string | undefined | null>,
) => {
    return [
        'Systems',
        computerSystemId,
        'LogServices',
        logServiceId,
        'Entries',
    ] as const;
};

export const getGetSystemLogServiceEntriesQueryOptions = <
    TData = Awaited<ReturnType<typeof getSystemLogServiceEntries>>,
    TError = RedfishError,
>(
    computerSystemId: MaybeRef<string | undefined | null>,
    logServiceId: MaybeRef<string | undefined | null>,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getSystemLogServiceEntries>>,
                TError,
                TData
            >
        >;
    },
) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = getGetSystemLogServiceEntriesQueryKey(
        computerSystemId,
        logServiceId,
    );

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getSystemLogServiceEntries>>
    > = ({ signal }) =>
        getSystemLogServiceEntries(computerSystemId, logServiceId, signal);

    return {
        queryKey,
        queryFn,
        enabled: computed(
            () => !!(unref(computerSystemId) && unref(logServiceId)),
        ),
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getSystemLogServiceEntries>>,
        TError,
        TData
    >;
};

export const getTaskServiceTasks = (signal?: AbortSignal) => {
    return apiInstance<TaskCollection>({
        url: `/redfish/v1/TaskService/Tasks`,
        method: 'GET',
        signal,
    });
};

export const getGetTaskServiceTasksQueryKey = () => {
    return ['TaskService', 'Tasks'] as const;
};

export const getGetTaskServiceTasksQueryOptions = <
    TData = Awaited<ReturnType<typeof getTaskServiceTasks>>,
    TError = RedfishError,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof getTaskServiceTasks>>,
            TError,
            TData
        >
    >;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = getGetTaskServiceTasksQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getTaskServiceTasks>>
    > = ({ signal }) => getTaskServiceTasks(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getTaskServiceTasks>>,
        TError,
        TData
    >;
};

export type GetTaskServiceTasksQueryResult = NonNullable<
    Awaited<ReturnType<typeof getTaskServiceTasks>>
>;
export type GetTaskServiceTasksQueryError = RedfishError;

export function useGetTaskServiceTasks<
    TData = Awaited<ReturnType<typeof getTaskServiceTasks>>,
    TError = RedfishError,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getTaskServiceTasks>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetTaskServiceTasksQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = unref(queryOptions).queryKey as DataTag<
        QueryKey,
        TData,
        TError
    >;

    return query;
}

export const getTaskServiceTaskById = (
    taskId: MaybeRef<string | undefined | null>,
    signal?: AbortSignal,
) => {
    taskId = unref(taskId);

    return apiInstance<Task>({
        url: `/redfish/v1/TaskService/Tasks/${encodeURIComponent(String(taskId))}`,
        method: 'GET',
        signal,
    });
};

export const getGetTaskServiceTaskByIdQueryKey = (
    taskId?: MaybeRef<string | undefined | null>,
) => {
    return ['TaskService', 'Tasks', taskId] as const;
};

export const getGetTaskServiceTaskByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getTaskServiceTaskById>>,
    TError = RedfishError,
>(
    taskId: MaybeRef<string | undefined | null>,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getTaskServiceTaskById>>,
                TError,
                TData
            >
        >;
    },
) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = getGetTaskServiceTaskByIdQueryKey(taskId);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getTaskServiceTaskById>>
    > = ({ signal }) => getTaskServiceTaskById(taskId, signal);

    return {
        queryKey,
        queryFn,
        enabled: computed(() => !!unref(taskId)),
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getTaskServiceTaskById>>,
        TError,
        TData
    >;
};

export type GetTaskServiceTaskByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getTaskServiceTaskById>>
>;
export type GetTaskServiceTaskByIdQueryError = RedfishError;

export function useGetTaskServiceTaskById<
    TData = Awaited<ReturnType<typeof getTaskServiceTaskById>>,
    TError = RedfishError,
>(
    taskId: MaybeRef<string | undefined | null>,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getTaskServiceTaskById>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetTaskServiceTaskByIdQueryOptions(taskId, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = unref(queryOptions).queryKey as DataTag<
        QueryKey,
        TData,
        TError
    >;

    return query;
}

export const getTelemetryServiceMetricReports = (signal?: AbortSignal) => {
    return apiInstance<MetricReportCollection>({
        url: `/redfish/v1/TelemetryService/MetricReports`,
        method: 'GET',
        signal,
    });
};

export const getGetTelemetryServiceMetricReportsQueryKey = () => {
    return ['TelemetryService', 'MetricReports'] as const;
};

export const getGetTelemetryServiceMetricReportsQueryOptions = <
    TData = Awaited<ReturnType<typeof getTelemetryServiceMetricReports>>,
    TError = RedfishError,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof getTelemetryServiceMetricReports>>,
            TError,
            TData
        >
    >;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = getGetTelemetryServiceMetricReportsQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getTelemetryServiceMetricReports>>
    > = ({ signal }) => getTelemetryServiceMetricReports(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getTelemetryServiceMetricReports>>,
        TError,
        TData
    >;
};

export type GetTelemetryServiceMetricReportsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getTelemetryServiceMetricReports>>
>;
export type GetTelemetryServiceMetricReportsQueryError = RedfishError;

export function useGetTelemetryServiceMetricReports<
    TData = Awaited<ReturnType<typeof getTelemetryServiceMetricReports>>,
    TError = RedfishError,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getTelemetryServiceMetricReports>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions =
        getGetTelemetryServiceMetricReportsQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = unref(queryOptions).queryKey as DataTag<
        QueryKey,
        TData,
        TError
    >;

    return query;
}

export const getUpdateService = (signal?: AbortSignal) => {
    return apiInstance<UpdateService>({
        url: `/redfish/v1/UpdateService`,
        method: 'GET',
        signal,
    });
};

export const getGetUpdateServiceQueryKey = () => {
    return ['UpdateService'] as const;
};

export const getGetUpdateServiceQueryOptions = <
    TData = Awaited<ReturnType<typeof getUpdateService>>,
    TError = RedfishError,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof getUpdateService>>,
            TError,
            TData
        >
    >;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = getGetUpdateServiceQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getUpdateService>>
    > = ({ signal }) => getUpdateService(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getUpdateService>>,
        TError,
        TData
    >;
};


// ========== Privilege Metadata (auto-generated) ==========
// This metadata enables runtime privilege checking.
// Entity names are derived from apiInstance<ReturnType>.

Object.defineProperty(getServiceRoot, 'privilegeMetadata', {
    value: { entity: 'ServiceRoot', method: 'GET' },
    writable: false,
});
Object.defineProperty(getAccountService, 'privilegeMetadata', {
    value: { entity: 'AccountService', method: 'GET' },
    writable: false,
});
Object.defineProperty(patchAccountService, 'privilegeMetadata', {
    value: { entity: 'AccountService', method: 'PATCH' },
    writable: false,
});
Object.defineProperty(getAccountServiceAccountById, 'privilegeMetadata', {
    value: { entity: 'ManagerAccount', method: 'GET' },
    writable: false,
});
Object.defineProperty(getManagers, 'privilegeMetadata', {
    value: { entity: 'ManagerCollection', method: 'GET' },
    writable: false,
});
Object.defineProperty(getManagersById, 'privilegeMetadata', {
    value: { entity: 'Manager', method: 'GET' },
    writable: false,
});
Object.defineProperty(getSystems, 'privilegeMetadata', {
    value: { entity: 'ComputerSystemCollection', method: 'GET' },
    writable: false,
});
Object.defineProperty(getSystemsById, 'privilegeMetadata', {
    value: { entity: 'ComputerSystem', method: 'GET' },
    writable: false,
});
Object.defineProperty(getSystemLogServices, 'privilegeMetadata', {
    value: { entity: 'LogServiceCollection', method: 'GET' },
    writable: false,
});
Object.defineProperty(getSystemLogServiceEntries, 'privilegeMetadata', {
    value: { entity: 'LogEntryCollection', method: 'GET' },
    writable: false,
});
Object.defineProperty(getTaskServiceTasks, 'privilegeMetadata', {
    value: { entity: 'TaskCollection', method: 'GET' },
    writable: false,
});
Object.defineProperty(getTaskServiceTaskById, 'privilegeMetadata', {
    value: { entity: 'Task', method: 'GET' },
    writable: false,
});
Object.defineProperty(getTelemetryServiceMetricReports, 'privilegeMetadata', {
    value: { entity: 'MetricReportCollection', method: 'GET' },
    writable: false,
});
Object.defineProperty(getUpdateService, 'privilegeMetadata', {
    value: { entity: 'UpdateService', method: 'GET' },
    writable: false,
});

